### DISCUSSION TITLE
Are subfolders in /config/templates/pages possible?

### DISCUSSION THREAD

**Discussion by brachycera** [sulu/sulu#6705] [Q&A] [answered]
Hello,

since I'm using a mulitpage Sulu setup with three Webspaces, I would like to create subfolders for the templates configuration in `/config/templates/pages` to keep everything tidy :broom: :wink:

Like this example:

`/config/templates/pages/project1/foo.xml`
`/config/templates/pages/project2/bar.xml`

I tried adding a path to `default-template` in the Webspace file `config/webspaces/project1.xml`

```xml
<default-templates>
   <default-template type="page">project1/foo</default-template>
</default-templates>
```

This triggers an error :construction: when validating the Webspace `php bin/adminconsole sulu:content:validate:webspaces`

```
The template "project1/foo" is not valid for the webspace "project1". Either it does not exist or was excluded from the webspace.
```

Is it possible to use subfolders or am I completely off :bowtie:

Thanks for any hint!

**Comment by alexander-schranz** [comment, marked as answer]
The `template` reference to the `<key>` which I recommend to use only `a-z` and `_` or `-` characters, not sure if that is currently validated. I would not try to give your template a key a character with `/` not sure if that would make any problems. 

So in your case I recommend to use `project1-default.xml` and `<key>project1-default</key>` and so on.

To include another directory then `config/templates/pages`. You need to register that directory you can configure the following in a `config/packages/sulu_core.yaml` file:

```yaml
sulu_core:
    content:
        structure:
            paths:
                page_project1:
                    path: '%kernel.project_dir%/config/templates/pages/project1'
                    type: page
                page_project2:
                    path: '%kernel.project_dir%/config/templates/pages/project1'
                    type: page
```

Subdirectories are not included by design, allows to use subdirectories for something else like xincluded xmls files.

Its even possible to configure different directory for the `webspaces.xml` there is currently only one directory possible:

```yaml
sulu_core:
    webspace:
        config_dir: '%kernel.project_dir%/config/webspaces'
```

We are example using this to have a monorepository for website who share the same codebase but are different are own installation and so have there own database. And we control the active webspace via `SITE` environment variable e.g.:

```yaml
sulu_core:
    webspace:
        config_dir: '%kernel.project_dir%/config/sites/%env(SITE)%'

sulu_core:
    content:
        structure:
            paths:
                page_site:
                    path: '%kernel.project_dir%/config/sites/%env(SITE)%/templates'
                    type: page
```

If this answers your question do you want to create a pull request for the https://docs.sulu.io/en/2.4/cookbook/override-dir-structure.html documentation? (targetting 2.4 branch)

**Comment by brachycera** [comment]
Hey @alexander-schranz, sorry but I'm back with some questions about the above solution :innocent:

As suggested I created the settings file `config/packages/sulu_core.yaml`
```yaml
sulu_core:
    content:
        structure:
            paths:
                page_project1:
                    path: '%kernel.project_dir%/config/templates/pages/project1'
                    type: page
                page_project2:
                    path: '%kernel.project_dir%/config/templates/pages/project2'
                    type: page
```
I also created the files & folder structure for the templates configurations as defined in the sulu_core.yaml.

`/config/templates/pages/project1/project1-default.xml` and `/config/templates/pages/project2/project2-default.xml`

The files content is the same as the sulu default.xml, except for:
```xml
    <key>project1-default</key>

    <view>pages/project1-default</view>
```


This brings me to the first question. When I now try to edit a `project1` page in the backend. The dropdown menu for the templates now displays `default` (=sulu's default template), `project1-default`and `project2-default` template. Although there is only the `project1-default` template defined in the webspace xml file.
I saw in the docs that I can exclude templates in the webspace xml file - which works but kind of defeats the purpose :wink:

`/config/webspace/project1.xml`
```xml
    <default-templates>
        <default-template type="page">project1-default</default-template>
        <default-template type="home">homepage</default-template>
    </default-templates>
<!-- 
    <excluded-templates>
        <excluded-template>default</excluded-template>
        <excluded-template>project2-default</excluded-template>
    </excluded-templates>
 -->
```

The next problem I ran into, when I select one of the project1/2 default templates, sulu triggers an exeption. Selecting the sulu default template works flawless.
```
Argument 2 passed to Sulu\Component\Content\Compat\StructureManager::wrapStructure() must be an instance of Sulu\Component\Content\Metadata\StructureMetadata, null given, 

called in /Sites/sulu/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Preview/PageRouteDefaultsProvider.php on line 96
```
Please note that I installed `sulu_themes`. 

Maybe sulu doesn't find the `twig` file for the requested template. When I move the `project1-default.xml` from the `/config/templates/pages/project1` folder to the default `/config/templates/pages/` the exception isn't triggered.

I also tried to add the templates folders to the `config/twig.yaml` and add the path to the xml files but this was without success.
```yaml
twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
      '%kernel.project_dir%/themes/project1/templates': 'project1'
      '%kernel.project_dir%/themes/project2/templates': 'project2'
```
`project1-default.xml`
```xml
<view>@project1/pages/project1-default</view>
```

I hope my explanation makes kind of sense and you have an idea why this doesn't work as expected. Thanks in advance!


Edit:
After a little testing, it looks like the exception is raised because the template doesn't belong to the selected webspace.
