### DISCUSSION TITLE
Sulu and Sentry.io

### DISCUSSION THREAD

**Discussion by fnagel** [sulu/sulu#7650] [Q&A] [answered]
Has somebody used Sulu CMS together with Sentry?

I've tried to implement it into my existing Sulu project but after installing sentry clearing the cache with `php bin/console cache:clear` fails with a "Segmentation fault (core dumped)" error. Any ideas whats the issue here?

https://docs.sentry.io/platforms/php/guides/symfony/

**Comment by alexander-schranz** [comment]
We are using Sentry in a few projects and as I did [update](https://github.com/getsentry/sentry-docs/pulls?q=is%3Apr+author%3Aalexander-schranz+is%3Aclosed) the linked documentation I can say that we are doing it that way it is documented.

A `Segmentation fault (core dumped)` is normally deeper problem in the compiled PHP version. Is the segmentation problem only happening on a Dev machine or also on a Prod / Stage machine? On dev maybe issue. Did you configure the sentry bundle error listener and handler correctly to false when used with monolog: https://docs.sentry.io/platforms/php/guides/symfony/integrations/monolog/ 

PS: Our Demo also has Sentry configured: https://github.com/search?q=repo%3Asulu%2Fsulu-demo%20sentry&type=code

**Comment by fnagel** [comment]
It's happening on my local Docker powered server as well as on the PROD server. Both have a similar setup, but this is my local machine:

PHP: 8.2.19
symfony/*: 6.4.14
sulu/sulu: 2.5.21
sentry/sentry-symfony: 5.0.1
sentry/sentry: 4.1.0

Same issue when downgrading to sentry/sentry-symfony v4.14.0

This is my sentry yaml: 
```
when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            ignore_exceptions:
                - 'Symfony\Component\ErrorHandler\Error\FatalError'
                - 'Symfony\Component\Debug\Exception\FatalErrorException'

        register_error_listener: false # Disables the ErrorListener to avoid duplicated log in sentry
        register_error_handler: false # Disables the ErrorListener, ExceptionListener and FatalErrorListener integrations of the base PHP SDK

    services:
        # (Optionally) Configure the breadcrumb handler as a service (needed for the breadcrumb Monolog handler)
        Sentry\Monolog\BreadcrumbHandler:
            arguments:
                - '@Sentry\State\HubInterface'
                - !php/const Monolog\Logger::INFO # Configures the level of messages to capture as breadcrumbs

    monolog:
        handlers:
            # (Optionally) Register the breadcrumb handler as a Monolog handler
            sentry_breadcrumbs:
                type: service
                name: sentry_breadcrumbs
                id: Sentry\Monolog\BreadcrumbHandler

            # Register the handler as a Monolog handler to capture messages as events
            sentry:
                type: sentry
                level: !php/const Monolog\Logger::ERROR # Configures the level of messages to capture as events
                hub_id: Sentry\State\HubInterface
                fill_extra_context: true # Enables sending monolog context to Sentry
                process_psr_3_messages: false # Disables the resolution of PSR-3 placeholders in reported messages

```

This is my monolog yaml: 
```
monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - attribute
        - scraper
        - import
        - google


when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: main_grouped
                excluded_http_codes: [404, 405]
                buffer_size: 100
                channels: ["!deprecation", "!attribute", "!eight_points_guzzle", "!scraper", "!import", "!google"]
            main_grouped:
                type: group
                members: [main_file, mail_deduplicated]
            main_file:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/symfony.log"
                level: debug
                max_files: 365

            attribute:
                type: fingers_crossed
                action_level: notice
                handler: attribute_grouped
                buffer_size: 100
                channels: ["attribute", "eight_points_guzzle", "scraper"]
            attribute_grouped:
                type: group
                members: [attribute_file, mail_deduplicated]
            attribute_file:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/attribute.log"
                level: notice
                max_files: 365

            import:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/import.log"
                level: debug
                max_files: 365
                channels: ["import"]

            google:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/google.log"
                level: info
                max_files: 365
                channels: ["google"]

            mail_deduplicated:
                type: deduplication
                time: 10
                handler: mail_symfony
            mail_symfony:
                type: symfony_mailer
                from_email: "%env(MAILER_SENDER_EMAIL)%"
                to_email: "%env(SULU_ADMIN_EMAIL)%"
                subject: 'Error:'
                level: warning
                formatter: monolog.formatter.html
                content_type: text/html

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
```
