### ISSUE TITLE
Configure prefixes of route names generated by FOSRestBundle

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1502]
The rest routes are generated by the fosrest bundle e.g. `get<resource_name>`

It would be good to prefix our sulu routes with the `name_prefix`. This will avoid that other bundles accidentally overwrite sulu routes.

**Comment by alexander-schranz** [comment]
In our new project we has this conflict as we have an own Category Entity which now overwrites the sulu route accidently. I would really prefer to prefix the routes in sulu core with its bundle prefix which we also use in normal route definitions:  /cc @sulu/core-team 

# Before:

```yml
sulu_category.categories:
    type: rest
    resource: Sulu\Bundle\CategoryBundle\Controller\CategoryController
```

Output:

```
 Name                                        Method   Scheme   Host   Path
 get_categories                              GET      ANY      ANY    /admin/api/categories.{_format}
```

# After:

```yml
sulu_category.categories:
    name_prefix: sulu_category.
    type: rest
    resource: Sulu\Bundle\CategoryBundle\Controller\CategoryController
```

Output:

```
 Name                                        Method   Scheme   Host   Path
 sulu_category.get_categories                              GET      ANY      ANY    /admin/api/categories.{_format}
```
