### ISSUE TITLE
Theme Templates Enhancements

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1966]
For pages and co it would be good to say where the template is without knowing in which bundle the theme will be. 

This can be done by adding the assetic bundles to liip theme app_resources. It would be good if sulu automaticly add `Assetic` Bundles to Liip Theme `app_resource`.

```yml
liip_theme:
    path_patterns:
        app_resource:
            - %%app_path%%/../../src/Client/Bundle/WebsiteBundle/Resources/themes/%%current_theme%%/%%template%%
```

So you can input in the Pages Template for <view> `::templates/default` instead of `ClientWebsiteBundle:templates:default`. The old view param would still work so it would not be a BC Break.

Its also a big advantage when you make reusable bundles e.g.: LoginBundle so you only need to render `::templates/login.html.twig` and the liip theme bundle will find the correct template for the current theme.
