### ISSUE TITLE
Routes with type portal can not used easily in security

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1968]
```yml
security:
    firewalls:
        website:
            form_login:
                login_path: my_bundle.login # only works with sulu.lo.my_bundle.login
                check_path: my_bundle.login_check # sulu.lo.my_bundle.login_check
```

As the prefix key of the generate route is the portalUrl the security yml need to be difference in dev or prod.
