### ISSUE TITLE
Custom-Routes prefix

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#2385]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.2 |
| Browser Version | all |
#### Actual Behavior

Custom-routes (like search) in the example currently also matches for longer prefixes.
- http://sulu.lo/de/search?q=Homepage
- http://sulu.lo/de/test/search?q=Homepage
#### Expected Behavior

The first one is good but the second one should no match.
#### Steps to Reproduce

Use sulu-standard and browse to the given urls above.
#### Possible Solutions

RequestListener which checks the prefixes in combination with the host after matching the route.

**Comment by alexander-schranz** [comment]
The redirect when no language is given seems also to be broken: http://demo.sulu.io/search?q=test

**Comment by wachterjohannes** [comment]
@alexander-schranz this will be fixed in the linked PR https://github.com/sulu/sulu/issues/2384

**Comment by alexander-schranz** [comment]
Have a problem which I think have todo with this issue.

I have 2 routes `/example` and `/more/{example}`.  
The url `/more/example´ will access the first controller this should not happen.

**Comment by wachterjohannes** [comment]
@alexander-schranz can you paste you route-config here?

**Comment by alexander-schranz** [comment]
Here is my configuration included as type `portal`:

```yml
# Login
l91_sulu_website_user.login:
    path: /login
    defaults:
        _controller: L91SuluWebsiteUserBundle:Login:login

# Cross Registration
l91_sulu_website_user.cross_registration:
    path: /registration/{webSpaceKey}
    defaults:
        _controller: L91SuluWebsiteUserBundle:CrossRegistration:crossRegistration
```

The called url is `/en/registration/login`. Temporarily i fixed it by change the order.
