### ISSUE TITLE
System collection not working behind http authentication

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2511]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.2 |
#### Actual Behavior

When you have a simple controller with http authentication system collection manager will fail to load the system collection.
#### Expected Behavior

Should just return the collection.
#### Steps to Reproduce
1. Create a system collection: http://docs.sulu.io/en/latest/cookbook/system-collections.html
2. add security bundle to website kernel
3. create a simple security file:

``` yml
security:
    providers:
        in_memory:
            memory:
                users:
                    dif2016:
                        password: test
                        roles: 'ROLE_USER'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        default:
            anonymous: ~
            http_basic: ~
    access_control:
        - { path: ^/collection, roles: ROLE_USER }
```
1. create a controller

``` php
<?php

namespace Alex\Bundle\WebsiteBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class CollectionController extends Controller
{
    /**
     * @param Request $request
     *
     * @return Response
     */
    public function getAction(Request $request, $collection)
    {
        $systemCollectionManager = $this->get('sulu_media.system_collections.manager');

        $collection = $systemCollectionManager->getSystemCollection($collection);
    }
}
```
1. `Attempted to call an undefined method named "getId" of class "Symfony\Component\Security\Core\User\User".` call the route and it will error with `vendor\sulu\sulu\src\Sulu\Component\Media\SystemCollections\SystemCollectionManager.php at line 139`
#### Possible Solutions

Check if user is from sulu user interface.
