### ISSUE TITLE
Route generate conditions for RoutableInterface entities

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2714]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| BC Break? | yes
| Sulu Version | 1.3.0-RC2

#### Actual Behavior

Actual the `setRoute` method of `Sulu\Bundle\RouteBundle\Model\RoutableInterface` default implementation is not nullable. You can set the `=  null` on your custom entity but I think the Interface should be the with the `= null`. PHP will not error so this is currently no bug. Currently you can not set a condition when a route for an entity should be generated.

#### Expected Behavior

setRoute should be:

```php
public function setRoute(RouteInterface $route = null);
```

conditions could be something like this:

```yml
# Sulu Routing
sulu_route:
    mappings:
        SomeEntity:
            route_schema: /entity/{object.getTitle()}
            condition: {object.isPublished()}
```

#### Steps to Reproduce

```php
$entity->setRoute(null);
```
