### ISSUE TITLE
Suggestion to improve adminbundle SCSS

### ISSUE THREAD

**Issue by Arjen-Smit** [sulu/sulu#2926]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | any |
| Browser Version | any |

Currently the best way to add custom branding to the sulu adminbundle is by loading a stylesheet with additional overwriting rules after loading the default stylesheet. Although this works in most cases I think there is a more elegant way to approach this.

There is a way to make some changes that wont break any current styling but that can be used to easily overwrite colors or images.

If you take for example this small snippet from base.scss

``` scss
.initial-loader {
    $dimension: 100px;
    width: $dimension;
    height: $dimension;
    @include centerBlock();
    .bouncer {
        background: $grayLighter;
    }
}
```

Could be changed to:

``` scss
// top of the file
$inital-loader-background: $greyLighter !default;


.initial-loader {
    $dimension: 100px;
    width: $dimension;
    height: $dimension;
    @include centerBlock();
    .bouncer {
        background: $inital-loader-background;
    }
}
```

The !default will use the value $greyLighter unless the variable is already set before this line.
This way you can add a file to your own project that looks something like this:

``` scss
$inital-loader-background: #b6b7ca;

@import '/path-to-sulu-bundle/scss/main';

```

This will result in a css file that is simular to the original adminbundle css file but with other colors (or images). Another great thing about this way of working is that a structural change in the scss of the admin bundle won't cause any conflicts with the overwrites that are normally done afterwards since they simply use the new structure but with correct already defined variables.

Any comments or suggestion to this sugestion are welcome, and if we can agree on this I don't mind doing some of the refactoring to make all colors and image configurable.

**Comment by danrot** [comment]
Really like the idea, using colors directly is not the best idea anyway. But I would use the camel case notation instead of connection the words using dashes, since it's already like that for the color itself (`greyLighter`).

**Comment by Arjen-Smit** [comment]
I personally prefer hyphenated variables but I'm fine with camelCase as well. I'll start working on a PR but if anyone has any more suggestions feel free to discuss them.

**Comment by danrot** [comment]
For me consistency is more important than personal taste 😃

**Comment by dvdweel** [comment]
@danrot 

Maybe it is a good idea to think about the variable names. 

If we take for example this snippet from login.scss

```css
.success-overlay {
            height: 100%;
            width: 100%;
            position: relative;
            z-index: -10;

            background-color: $green; 
        }
```

And would change it the way @Arjen-Smit  is suggesting. You can end up with very long variable names.

```css
$suluLoginContentContainerSuccessOverlayBackgroundColor: $green !default;

.success-overlay {
            height: 100%;
            width: 100%;
            position: relative;
            z-index: -10;

            background-color: $suluLoginContentContainerSuccessOverlayBackgroundColor;
        }
```


Maybe it is better to shorten the names so it would be easier to understand. There are some parts of the variable that are unnecessary and without them we still know what value we want to change.

Personally I would change
```css
$suluLoginContentContainerSuccessOverlayBackgroundColor: $green !default;
```

to

```css
$LoginSuccessOverlayBackgroundColor: $green !default;
```

This way we still can overwrite the values without using very long variable names.
What do you think will be the best approach?
