### ISSUE TITLE
Infinite scroll in collection navigation only loads next page once

### ISSUE THREAD

**Issue by reflexxion** [sulu/sulu#2937]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.1 |
#### Actual Behavior

When some collection has more then 40 items, infinite scroll only loads the next page once.
So at the first request it loads 20 collections. Scrolling to the bottom it loads another 20. Then scrolling again to bottom it doesn't load the next page. 
#### Expected Behavior

Load all pages until last item is reached.
#### Steps to Reproduce

Having a collection tree like this:

``` yaml
root_collection:
  sub_collection: # 2016
    child_collection: # 2016_09
      - child_child_collection1 # some named collections
      - ... 
      - child_child_collection60
```

Navigating from `root_collection` to `sub_collection` and `child_collection`. 
Inside of the collection navigation scroll to bottom twice.
