### ISSUE TITLE
Add default path to overwrite excerpt extension

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3093]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.4

#### Actual Behavior

Currently you need to configure following to overwrite the excerpt structure:

```yml
sulu_core:
    content:
        structure:
            paths:
                <some_value>:
                    path: "%kernel.root_dir%/../src/AppBundle/Content/templates"
                    type: "page"
```

This has the disadvantage that path is from project to project different.

#### Expected Behavior

I would pretend the following configuration for the excerpt:

```yml
sulu_core:
    content:
        structure:
            paths:
                extensions: # not sure if this key conflicts with the default.
                    path: "%kernel.root_dir%/Resources/templates/extensions"
                    type: "page"
```

So he only need to create the `excerpt.xml` in the folder to overwrite it.

#### Steps to Reproduce

See Actual Behaviour.

#### Possible Solutions

Prepend the configuration. To allow overwritting the excerpt.xml
