### ISSUE TITLE
Search Index entries for Media not removed in Elasticsearch

### ISSUE THREAD

**Issue by adsc-cloudtec** [sulu/sulu#3493]
I have verified this behaviour in Sulu 1.6.3 both in sulu-minimal and sulu-standard basic installations (no configuration apart from renaming the webspaces and page templates). Elasticsearch version used is 2.4.6. 

Searchbundle configuration:
```yml
# Massive Bundles
massive_search:
    adapter: elastic
    adapters:
        elastic:
            hosts: [ myhost.com:9200 ]
            version: 5.0
    metadata:
        prefix: sulu
    persistence:
        doctrine_orm:
            enabled: true
```

With this configuration, search entries for Media are added into Elasticsearch, but when the Media is removed in the Sulu admin interface, the Elasticsearch entry is not removed. This only happens with Media type entities, pages for example are removed from Elasticsearch just fine.

I have debugged a bit into the code and noticed that `SearchManager` throws a `MetadataNotFoundException` around line 99, which is then caught in `DeindexListener` but ignored.
