### ISSUE TITLE
Website session overwrite admins session and user get logged out

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3680]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.9

#### Actual Behavior

When the website uses sessions for e.g. for Forms (CSRF Token) or Community Bundle. It could happen that the preview overwrite the admin session because admin and website has the same cookie name.

#### Expected Behavior

The admin session should not been overwritten by the website session and vice versa.

#### Steps to Reproduce

Access session on the website. 

#### Possible Solutions

**A. Use different cookie names**

https://symfony.com/doc/current/reference/configuration/framework.html#name

`app/config/admin/config.yml`:

```yml
framework:
    session:
        name: PHPSESS_ADMIN
```

Will break exist varnish or other cache tool configuration which remove all unknown cookies from the response. 

**B. Use same session storage for admin and website**

This is the solution I currently choice for my project by removing the sulu.context parameter from the session path:

`app/config/config.yml`:

```yml
framework:
    session:
        save_path: "%kernel.var_dir%/sessions/%kernel.environment%"
```

https://github.com/sulu/sulu-minimal/blob/1.6.9/app/config/config.yml#L28

Currently we use in some projects redis which also configured to share admin and website sessions mostly.

**C. Set cookie_path**

https://symfony.com/doc/current/reference/configuration/framework.html#cookie-path

At time writing this issue I did come over the cookie path which could also be solution.

`app/config/admin/config.yml`:

```yml
framework:
    session:
        cookie_path: /admin
```

https://github.com/sulu/sulu-minimal/pull/78/files
