### ISSUE TITLE
WIP: Sulu Image optimization

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3729]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6.13

### Actual Behavior

Currently the image which are generated by imagine are not optimized and can end in high file size. You can only configure a jpeg_quality and png_compression_level:

```
sulu_media:
    format_manager:
        default_imagine_options:
            jpeg_quality: 85
            png_compression_level: 6
```

or for a format:

```
    <format key="940x-90">
        <scale x="940"/>
        <options>
            <option name="jpeg_quality">90</option>
        </options>
    </format>
```

### Expected Behavior

The images should be optimized with different tools when available.

### Steps to Reproduce

Upload an optimized image and return the same image processed by imagine it will end in a higher file size as the original.

#### JPEG Quality from Original

When the `jpeg_quality` is configured for example to `100%` and the original image has a a lower `jpeg_quality` e.g. `80%` it should use the one from the original image? This should be configureable and set by default to false as this will not always make sense for example for very small images you maybe don't want a very small jpeg_quality.

**Example** how this could be configured globally:

```
sulu_media:
    format_manager:
        default_imagine_options:
            jpeg_quality: 85
            png_compression_level: 6
            jpeg_quality_inheritance: true
            png_compression_level_inheritance: true
```

**Example** how this could be configured per format:

```
    <format key="940x-90">
        <scale x="940"/>
        <options>
            <option name="jpeg_quality">90</option>
            <option name="jpeg_quality_inheritance">true</option>
            <option name="png_compression_level">6</option>
            <option name="png_compression_level_inheritance">true</option>
        </options>
    </format>
```

#### Post Processor

The name is inspired by the LiipImagine bundle where PostProcessors are tools which are called after the image is generated: https://symfony.com/doc/2.0/bundles/LiipImagineBundle/post-processors.html.

There exist some tools:

 - https://github.com/bensquire/php-image-optim
 - https://github.com/spatie/image-optimizer
 - https://github.com/lciolecki/php-image-optimizer

The disadvantage of mostly all tools are that they need an exist binary installed on the server so all post processors need to be optional and needed to be configured by the developer.

**Example** how post processors could be configured:

```
sulu_media:
    postprocessors:
        # Gif optimization tools
        gifcycle:
            binary: /usr/local/bin/gifcycle
        # Png optimization tools
        advpng:
            binary: /usr/local/bin/advpng
        pngcrush:
            binary: /usr/local/bin/pngcrush
        pngout:
            binary: /usr/local/bin/pngout
        pngquant:
            binary: /usr/local/bin/pngquant
        optipng:
            binary: /usr/local/bin/optipng
        pngcrush:
            binary: /usr/local/bin/pngcrush
```

This issue is to be continued ....
