### ISSUE TITLE
Allow overriding of route class of prepended configuration

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3839]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

#### Actual Behavior

Currently you can't prepend route definition and overwrite them with your configuration.

#### Expected Behavior

It should be possible to overwrite the route class.

#### Steps to Reproduce

Prepend a configuration in a bundle (https://github.com/sulu/SuluArticleBundle/blob/9311a1a4aef7527ffce46c14f32a5a68232f969c/DependencyInjection/SuluArticleExtension.php#L108-L121):

You are not able to overwrite the class:

```yml
sulu_route:
    mappings:
        AppBundle\Document\ArticlePageDocument:
            generator: ...
```

#### Possible Solutions

It should use not the class as key there should be a key introduced:

```yml
sulu_route:
    mappings:
        article_page:
            class: AppBundle\Document\ArticlePageDocument:
            generator: ...
```

**Comment by alexander-schranz** [comment]
As we use: [useAttributeAsKey](http://symfony.com/doc/3.4/components/config/definition.html#array-node-options) we can overwrite this with:

```
sulu_route:
    mappings:
        Sulu\Bundle\ArticleBundle\Document\ArticleDocument:
            className: AppBundle\Document\ArticleDocument
            generator: schema
            options:
                route_schema: "/{object.getTitle()}"
```
