### ISSUE TITLE
Ability to browse each snippet type independently

### ISSUE THREAD

**Issue by AcelisWeaven** [sulu/sulu#4278]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | --
| Browser Version | --

#### Actual Behavior

All snippets can be found on the "Snippets" tab, and can't be filtered.

#### Expected Behavior

Every snippet should be manageable independently. This has been mentioned in #3235, where @trickreich suggested to have each snippet in its own tab, like in SuluArticleBundle. (I don't know how it looks like, never had more than one article type)

In a project on Sulu 1.6, I created a small bundle to change the menu dynamically, depending on my snippet configuration. In my sample implementation, snippet can be grouped by category. Here's an example of a tag that made the snippet appear here:
`<tag name="separated" category="snippet.category.addresses" icon="home"/>`

![screenshot from 2018-11-15 10-25-29](https://user-images.githubusercontent.com/6735195/48560172-86b98b00-e8ed-11e8-8b08-3dca5c67775f.png)

Pros:
- manageable at the snippet level (in the xml file)
- not every snippet have to appear in the menu (if the tag is not here, it'll only be accessible via the snippet menu)

Cons:
- phpcr may have performance issues when filtering by type (slower back-end)
- defining the group icon at the snippet level is not a good idea

#### Possible Solutions

The ability to handle this problem at the snippet level has its limits when you have snippet groups, but it would be fine if you have one tab per snippet.

An hybrid solution could also work. Let's say you add a tag like `<tag name="sulu.snippet.isolate">`: the snippet would appear as its own menu entry.
Now, let's say I have two snippets and I want group them under the same menu entry. This could be done at the configuration level:
```yml
sulu_snippet:
    menu:
        group1:
            icon: 'puzzle'
            snippets: ['snippet1', 'snippet2']
```

Also, the xml tag could be completely left out, and everything could be done in the configuration file.
```yml
sulu_snippet:
    menu:
        snippet1:
            icon: 'home'
        group1:
            icon: 'puzzle'
            snippets: ['snippet2', 'snippet3']
```
This would look like that:
![screenshot from 2018-11-15 16-03-17](https://user-images.githubusercontent.com/6735195/48561349-0a747700-e8f0-11e8-85d0-904c13d1d86f.png)

This is a feature I'd really like to have in Sulu 2.
