### ISSUE TITLE
[MediaBundle] format manager types configuration cannot be changed

### ISSUE THREAD

**Issue by markdehaan** [sulu/sulu#4343]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | <= 1.6.24, dev-develop
| Browser Version | All

#### Actual Behavior

Sulu crashes when trying to configure types under format_manager.

#### Expected Behavior

Sulu does not crash when configuring types for the format manager

#### Steps to Reproduce

Configure your types:

```
sulu_media:
    format_manager:
        types:
            -
                type: image
                mimeTypes:
                    - 'image/jpg'
```

#### Possible Solutions

Prototype scalar in Configuration.php should be changed to arrayPrototype.
