### ISSUE TITLE
Cannot change image of a contact person when localization "en" is not available

### ISSUE THREAD

**Issue by fdyckhoff** [sulu/sulu#4345]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.0-alpha4
| Browser Version | Firefox

#### Actual Behavior

When trying to add an image to a contact profile, the requests returns a permission error:

> Permission "add" in localization "en" for object with id "5" and of type "Sulu\Bundle\MediaBundle\Entity\Collection" not granted

Only "de" is enabled as localization in the webspace config and allowed for the current user 

```xml
    <localizations>
        <localization language="de" default="true"/>
    </localizations>
```

When I re-add and enable "en" as localization, the image upload for contact persons works again.

#### Expected Behavior

The media object should have been uploaded in the current selected language "de" - and not in "en" which is not available

#### Steps to Reproduce

1. set localization to "de" only in the webspace config
2. Edit contact "Adam Ministrator"
3. Upload an image
4. `POST /admin/api/media?locale=en&collection=5` results in 403 Forbidden; no error message is displayed for the user

#### Possible Solutions

-

**Comment by alexander-schranz** [comment]
@fdyckhoff At current state you can workaround this problem by using `de` also as default locale for your application with:

```yaml
# config/packages/framework.yaml
framework:
    default_locale: "%locale%"

# config/packages/sulu.yaml
sulu_core:
    fallback_locale: "%locale%"

# config/services.yaml
parameters:
    locale: de
```

@sulu/core-team I see 3 solutions:

1. check in which locale the user has permission for medias and use the first one
2. change the media api to allow no locale and use default locale to create the media then
3. add default locale to the permissions dropdown
