### ISSUE TITLE
The child node "index_name" at path "sulu_article" must be configured

### ISSUE THREAD

**Issue by zazz-will** [sulu/sulu#4839]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| SuluArticleBundle Version | dev-develop
| Sulu Version | 2.0.0

Hello,

I come to you because I saw that I could use SuluArticleBundle with Sulu 2.0.0, I am on Symfony 4.

I followed the installation document of the bundle, but when I go to the initialization step by doing "`php bin/console assets: install`" I have an error.

the mistake is this : `The child node "index_name" at path "sulu_article" must be configured.`

my conf : 
sulu_route.yaml : 

```
sulu_route:
    mappings:
        Sulu\Bundle\ArticleBundle\Document\ArticleDocument:
            generator: "schema"
            options:
                route_schema: "/articles/{object.getTitle()}"
        Sulu\Bundle\ArticleBundle\Document\ArticlePageDocument:
            generator: "article_page"
            options:
                route_schema: "/{translator.trans(\"page\")}-{object.getPageNumber()}"
                parent: "{object.getParent().getRoutePath()}"
```

sulu_core.yaml : 
```
sulu_core:
    locales:
        de: Deutsch
        en: English
        fr: Français
    translations:
        - de
        - en
        - fr
    fallback_locale: fr
    content:
        structure:
            default_type:
                article: "article_default"
            paths:
                article:
                    path: "%kernel.project_dir%/config/templates/articles"
                    type: "article"
```
ongr_elasticsearch.yaml : 
```
ongr_elasticsearch:
    analysis:
        tokenizer:
            pathTokenizer:
                type: path_hierarchy
        analyzer:
            pathAnalyzer:
                tokenizer: pathTokenizer
    managers:
        default:
            index:
                index_name: su_articles
            mappings:
                - SuluArticleBundle
        live:
            index:
                index_name: su_articles_live
            mappings:
                - SuluArticleBundle
```
sulu_admin.yaml in my routes folder: 
```
sulu_article_api:
    resource: "@SuluArticleBundle/Resources/config/routing_api.xml"
    type: rest
    prefix: /admin/api

sulu_article:
    resource: "@SuluArticleBundle/Resources/config/routing.xml"
    prefix: /admin/articles
```
sulu_article.yaml : 
```
sulu_article:
    default_main_webspace: 
        de: 'webspace'
        en: 'webspace'
        fr: 'webspace'
```

When I add index_name as follows : 
```
sulu_article:
    default_main_webspace: 
        de: 'webspace'
        en: 'webspace'
        fr: 'webspace'
    index_name: su_articles
```
I have the following error `article type(s) already defined in other document, you can use the same type only once in a manager definition.`

Have I forgotten something or made a mistake somewhere?

thank you for your answer
