### ISSUE TITLE
[WebsiteBundle] Create own dynamic router for content

### ISSUE THREAD

**Issue by sulu-io-user** [sulu/sulu#493]
<a href="https://github.com/danrot"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/405874?v=2" /></a>
By @danrot _from_ https://github.com/sulu-cmf/SuluWebsiteBundle/issues/25

Currently the config file for the routing looks like the following:

``` yaml
cmf_routing:
    chain:
        routers_by_id:
            router.default: 100
            cmf_routing.dynamic_router: 20
    dynamic:
        enabled: true
        route_provider_service_id: sulu_website.provider.portal
```

We should not use the `dynamic` option here, but instead create an own dynamic router as a service, and use that one in the `routers_by_id` configuration.
