### ISSUE TITLE
Editing and creating entities in selection field type

### ISSUE THREAD

**Issue by plozmun** [sulu/sulu#5143]
# Problem description

Now in sulu you can add snippets or custom entities but if you want to change a value in them you have to look for them and edit in another window. 

# Proposed solution

Add a new button near trash button to edit the content and open a popup if the edit view exists ( or maybe a link that section ). The problem may be a circular reference that would have to be controlled at 1 level perhaps. 
Extra for this feature will be inline creation :)

**Comment by danrot** [comment]
This includes #1904 and #1996, therefore I am going to close those two issues and keep this one.

I am adding the same response as their: I can imagine that we have a deep link functionality for the selection field type, but lettig the user create and edit such complex forms in an overlay is actually against our current design philosophy... We also try not to have overlays over overlays, which would be easily possible with that approach.

**Comment by TheCadien** [comment]
specially for snippets i realy love these feature see back again in feature !
like it was in sulu 1.6

**Comment by danrot** [comment]
I have created a small graphic in order to think about how to solve this. This shows what information is currently available in the three parts - search, selections and smart content - where we want to have deep links (hope I didn't forget about one).

![2020-04-14_DeepLinks](https://user-images.githubusercontent.com/405874/79201904-0cba6800-7e39-11ea-8b46-d19fe3b08b1d.png)

Currently deep links are only working for the search, where it was solved by introducing a mapping in the `sulu_search` configuration:

```yaml
sulu_search:                                                                                                                                                                                               
    indexes:                                                                                                                                                                                               
        snippet:                                  
            name: sulu_snippet.snippets
            icon: su-snippet
            view:                                 
                name: sulu_snippet.edit_form
                result_to_view:
                    id: id
                    locale: locale
```

Now multiple questions come up:

1. For the search we needed to define a locale to be passed, because there is no current locale selected. In the case of the selection and the smart content we could use the currently selected locale of the form (if available, which would make the handling a bit more cumbersome). The questions boils down to which language the deep link of a ghost page should link to. The currently selected language of the form, or to the language that was used for displaying the title?
2. We need some more information in the response for the smart content, e.g. the webspace for pages. I think we have to add a `properties` variable similar to the search, because the rest of the interface is standardized. But there are already child classes like `ContactDataItem`, `ContentDataItem`, which would be made obsolete when introducing the `properties` variable. Alternatively we could also add the missing properties to the `ContentDataItem` and add the `webspaceKey` on the same level as `title`, `publishedState`, etc.
3. How much do we want to abstract, resp. do we want to abstract this at all? We could create a mapping from `resourceKey` to the edit form, but the question is if that is worth it. The mapping for the route attributes probably needs to be done separately for search, selection and smart content, unless we unify the returned responses from the server. This could e.g. mean to add the `properties` property to every response, and fill it with at least the necessary fields to generate the route. Then something like a `DeepLink` service could be created, which might be called something like this:

```javascript
DeepLinkService.link(routeName, object);
```

The alternative is to simply use the router, but then we have to introduce a separate config for the mapping for search, selection and smart content, having the advantage that we don't have to touch the server's response.

```javascript
router.navigate(config.routeName, Object.keys(config.routeMapping).reduce(/* ... */);
```

/cc @sulu/core-team
