### ISSUE TITLE
WebpackEncoreBundle conflict with public/build/admin assets

### ISSUE THREAD

**Issue by davidromani** [sulu/sulu#5216]
| Q | A
| --- | ---
| Sulu Version | 2.0.6
| Browser Version | any

# Actual Behavior

After install `symfony/webpack-encore-bundle` to manage my frontend assets, every time that I run `$ yarn encore dev` command my backend (admin) assets are broken.

# Expected Behavior

I need to keep both (/public/build/admin and /public/build) compiled assets folders to ensure that admin area is working well. 

# Steps to Reproduce

* install sulu/skeleton
* composer require symfony/webpack-encore-bundle
* yarn install
* check that webpack.config.js file is installed in project root dir
*  yarn encore dev

**Comment by alexander-schranz** [comment]
@davidromani Thank you for creating an issue. That sadly an issue which with the webpack encore recipe, you need to change the `output_path` in the webpack encore configuration for your website:

```yaml
# config/packages/webpack_encore.yaml
webpack_encore:
    output_path: '%kernel.project_dir%/public/build/website'
```

```yaml
# webpack.config.js
     .setOutputPath('public/build/website/')
```

If your current configuration did accidentally remove the admin build you can get it back by using: `bin/console sulu-admin:download-build` if you did not have any admin related changes.

**Comment by davidromani** [comment]
Thanks @alexander-schranz it works!

Finally I found another place where you must configurate the new manifest.json location.

```
# config/packages/assets.yaml
framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/website/manifest.json'
```
