### ISSUE TITLE
Add the possibility to ignore a group of fixtures in Sulu Builder

### ISSUE THREAD

**Issue by plozmun** [sulu/sulu#5274]
# Problem description

In sulu 2.1RC fixtures changes and now have to be registered as `sulu.document_manager_fixture` but all fixtures are executed independently of the group.

# Proposed solution

Add default group for clean install or maybe ignore those who implements DocumentFixtureGroupInterface

**Comment by alexander-schranz** [comment]
Can you provide more information how you use the fixtures. Basically we say that `sulu:build` is run once for a project when installed, not in automatic deployment or elsewhere. In automatic deployments we run only phpcr migration and doctrine migration commands.
If you create test fixtures you can inject and `kernel.environment` and don't run fixtures in specific environments like you would do it in doctrine fixtures.

**Comment by plozmun** [comment]
We use fixtures to build pages with blocks and later make tests with panther or functional tests, that is the main reason. Doing it by environment is a good option but what is the utility of the groups then if they are always going to run?

**Comment by alexander-schranz** [comment]
@plozmun the features is there that you can directly install specific fixtures using its similar to doctrine fixtures bundle:

```bash
bin/console sulu:document:fixtures:load --append --group Group1
```

As said the sulu:build command is there for the first installation to have all what you need there to start development.

If you really want still depend on sulu:build in your tests I would just use another environment for the build process and exclude the fixtures you don't want to run as you will have the same todo with doctrine fixtures if you create them also doctrine entities.

**Comment by plozmun** [comment]
Okay! Got it! Currently we were also using it to put "fake" content in staging or development but maybe the phpcr migration option is more suitable. Thank you!

**Comment by alexander-schranz** [comment]
@plozmun you can still use fixtures:

Disable the test fixture namespace:

```yaml
# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,DataFixture/TestFixtures,Kernel.php}' # exclude test fixtures
```

Then `sulu:build` should not install it.

Enable it for a special environment:

```yaml
# config/services_testfixtures.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\DataFixture\Test:
        resource: '../DataFixture/TestFixtures/*'
```

Then use the special environment to install the specific fixture for the test you want:

```
bin/console sulu:document:fixtures:load --append --group Test1Fixture --env testfixtures
# or
bin/console sulu:document:fixtures:load --append --group Test2Fixture --env testfixtures
```
