### ISSUE TITLE
Preupload image resizing

### ISSUE THREAD

**Issue by josgerrits** [sulu/sulu#5300]
# Problem description

Some of our customers using Sulu 2.0 are uploading (or trying to upload) super large files (5mb+). However, the website only supports displaying images up to 1920px wide. So uploading these large files is useless and takes a hit on our server when uploading multiple of these large files.

# Proposed solution

We want to resize images before they are uploaded to the server. We want to use a package like https://www.npmjs.com/package/resize-image in the MediaUploadStore to resize images before they are uploaded. It would be nice to have configurations available like "preupload_enabled", "preupload_max_width", "preupload_max_height" and "preupload_compression".

Is this something you would consider implementing in Sulu 2? If so, we would like to contribute and make a PR. We just wanted to double check before we put in the time to develop this.

Thanks :)

**Comment by danrot** [comment]
That's an interesting idea! I like it, and don't see any reason not to implement this... The only downside that comes to my mind, is that if in the future a bigger format is defined, the quality of the image is worse than if the original image would have been uploaded. Maybe we should still warn the content manager about this?

@chirimoya WDYT about that idea?

**Comment by alexander-schranz** [comment]
I also find this a very interesting feature, but it need to be a opt-in feature as browser resizing will *throw away all metadata* of that image. So as long as not activated it should do nothing with the original image and just upload the original file. Also when resizing failed it should not error and upload the original file as we can not be sure that all browsers will support this correctly.

From the config it should be something like:

```yaml
sulu_media:
    pre_upload: 
        image_resize:
            enabled: true # defaults to false when nothing configured
            max_width: 1920 # in px and should be nullable
            max_height: null # in px and should be nullable
            compression: 100 # default 100
```

I would maybe in javascript introduce a additional registry so, maybe in future there are also other  use cases where we want to manipulate files before getting uploaded to avoid some processing on the server.

When looking at the linked library I would avoid that, the code itself is not worse to add a additional library to sulu which we are not sure how trustful it will be in future, so I would create an own service doing that instead of add a new library.

So I think if you are willing to provide this feature you can coordinate the implementation with @danrot
