### ISSUE TITLE
Display thumbnails in a select list with custom data

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#5401]
# Problem description

We query our shop's Elastic Search for Json Data and display that in sulu. That works very well!

Still when sulu rebuilds the previe list of selected products by querying the SKUs again, I want to display the product thumbnail in the list. But that doesn't work. It is always written [object Object]

![preview_select](https://user-images.githubusercontent.com/245385/87053783-aa3bf280-c202-11ea-81ef-541ab68ad60d.png)

# Proposed solution

Add the rendering of images.
[Probably to be found here as Luca told me.](https://github.com/sulu/sulu/blob/8bc80ee31f187e781180365ea656f621b9d6aa7f/src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/MultiSelection.js#L188)

I tried `display_properties: ["image", "eNumber", "name"]` and it won't work as expected

My code:

```
sulu_admin:
    field_type_options:
        selection:
            product_selection:
                default_type: "list_overlay"
                resource_key: "products"
                types:
                    list_overlay:
                        adapter: "table"
                        list_key: "products"
                        display_properties: ["eNumber", "name"]
                        icon: "fa-database"
                        label: "app_product.selection_label"
                        overlay_title: "app_product.selection_overlay_title"
```
```
<?xml version="1.0" ?>
<list xmlns="http://schemas.sulu.io/list-builder/list">
    <key>products</key>

    <properties>
        <property name="image" visibility="always" translation="app_product.image" type="thumbnails" sortable="false"/>

        <property name="id" visibility="no" translation="app_product.sku" searchability="no"/>

        <property name="eNumber" visibility="always" translation="app_product.eNumber" searchability="yes"/>

        <property name="name" visibility="always" searchability="yes" translation="app_product.name"/>
    </properties>
</list>
```
```
<?php declare(strict_types=1);

namespace App\Spryker;

use Symfony\Contracts\HttpClient\HttpClientInterface;

final class ProductLoader
{
    /**
     * @var HttpClientInterface
     */
    private $httpClient;

    /**
     * @var string
     */
    private $yvesUrl;

    /**
     * ProductGateway constructor.
     * @param HttpClientInterface $httpClient
     * @param string $yvesUrl
     */
    public function __construct(HttpClientInterface $httpClient, string $yvesUrl)
    {
        $this->httpClient = $httpClient;
        $this->yvesUrl = $yvesUrl;
    }

    public function findProducts(string $search): array
    {
        return $this->normalizeProducts($this->loadProducts($search));
    }

    public function findProductByIds(array $ids, bool $raw = false): array
    {
        $products = [];
        foreach ($ids as $id) {
            if($raw) {
                $products = array_merge($products, $this->loadProducts($id));
            } else {
                $products = array_merge($products, $this->normalizeProducts($this->loadProducts($id)));
            }
        }

        return $products;
    }

    private function loadProducts(string $searchString): array
    {
        $response = $this->httpClient->request(
            'POST',
            $this->yvesUrl.'/search',
            [
                'json' => [
                    'query' => $searchString,
                    ],

            ]
        );

        $data = \json_decode($response->getContent(), true);

        return $data['data']['products'];
    }

    private function normalizeProducts(array $products): array
    {
        $result = [];
        $skus = [];
        foreach ($products as $product) {
            if (in_array($product['sku'], $skus)) {
                continue;
            }

            $skus[] = $product['sku'];
            $result[] = [
                'id' => $product['sku'],
                'sku' => $product['sku'],
                'eNumber' => $product['eNumber'],
                'name' => $product['name'],
                'image' => ['sulu-40x40' => $product['image']['externalUrlSmall']],
            ];
        }

        return $result;
    }
}
```
