### ISSUE TITLE
Unable to run sulu:build dev after update from 2.1.2 to 2.2.2

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu#5688]
| Q | A
| --- | ---
| Sulu Version | 2.2.1

# Actual Behavior

2.1.2 runs fine. sulu:build dev shows no problems and after that I have an empty system. 
2.2.2 just fails during the installation with the error you can find below.

Error message is:  `[PHPCR\ItemNotFoundException]      Item /cmf/dy/contents not found in workspace default_live`

I can change branches and composer install to 2.1.2 and it runs fine. Switch back and it fails.

I merged all changes from the skeleton and did look up the UPDAGRADE.md. imho I am not missing anything.

The 87 DB Tables are created. No error here.         

# Expected Behavior

2.2.2 should provide an empty system like 2.1.2

# Steps to Reproduce

Good question. I believe it is probably my setup. Then again except PGSQL it is pretty standard in it's base and we just do use 5 Webspaces.


```➜  akona-cms git:(update-2.2.1) docker-compose exec php bin/adminconsole sulu:build dev -vvv
Build Targets
=============

+---+--------------------+---------------------------------------------------------------------------------+
| # | Builder            | Deps                                                                            |
+---+--------------------+---------------------------------------------------------------------------------+
| 0 | database           |                                                                                 |
| 1 | phpcr              | database                                                                        |
| 2 | phpcr_migrations   | phpcr                                                                           |
| 3 | fixtures           | database, phpcr                                                                 |
| 4 | user               | fixtures, database                                                              |
| 5 | system_collections | database, fixtures                                                              |
| 6 | security           | fixtures, database                                                              |
| 7 | dev                | database, fixtures, phpcr, user, phpcr_migrations, system_collections, security |
+---+--------------------+---------------------------------------------------------------------------------+

Options:

  - nodeps: false
  - keep-exit-code: false
  - destroy: false
  - help: false
  - quiet: false
  - verbose: true
  - version: false
  - ansi: false
  - no-ansi: false
  - no-interaction: false
  - env: 'dev'
  - no-debug: false

Look good? (y)

Executing builders
==================

Target: database

    doctrine:schema:update  ({"--force":true})
    
        
                 Updating database schema...
        
                     444 queries were executed
        
                                                                                                                                        
         [OK] Database schema updated successfully!                                                                             
                                                                                                                                
        
                
Target: phpcr

    sulu:document:initialize
    
        sulu_document_manager.initializer.workspace
          [+] workspace: "default"
          [+] workspace: "default_live"
        sulu_document_manager.initializer.root_path_purge_initializer
          [ ] Purging workspaces
        sulu_page.document_manager.content_initializer
          content namespaces:
          [+] sulu:http://sulu.io/phpcr
          [+] sec:http://sulu.io/phpcr/sec
          [+] settings:http://sulu.io/phpcr/settings
          [+] i18n:http://sulu.io/phpcr/locale
          content node types:
          [*] sulu:base
          [*] sulu:path
          [*] sulu:content
          [*] sulu:snippet
          [*] sulu:page
          [*] sulu:home
          content namespaces:
          [ ] sulu:http://sulu.io/phpcr
          [ ] sec:http://sulu.io/phpcr/sec
          [ ] settings:http://sulu.io/phpcr/settings
          [ ] i18n:http://sulu.io/phpcr/locale
          content node types:
          [*] sulu:base
          [*] sulu:path
          [*] sulu:content
          [*] sulu:snippet
          [*] sulu:page
          [*] sulu:home
        sulu_core.webspace.document_manager.webspace_initializer
          [+] homepage: [homepage] /cmf/dy/contents (fr)
        
        In Session.php line 289:
                                                                     
          [PHPCR\PathNotFoundException]                              
          Item /cmf/dy/contents not found in workspace default_live  
                                                                     
        
        Exception trace:
          at /var/www/project/vendor/jackalope/jackalope/src/Jackalope/Session.php:289
         Jackalope\Session->getNode() at /var/www/project/vendor/sulu/sulu/src/Sulu/Bundle/DocumentManagerBundle/Session/Session.php:84
         Sulu\Bundle\DocumentManagerBundle\Session\Session->getNode() at /var/www/project/vendor/sulu/sulu/src/Sulu/Component/Content/Document/Subscriber/SecuritySubscriber.php:220
         Sulu\Component\Content\Document\Subscriber\SecuritySubscriber->getLiveNode() at /var/www/project/vendor/sulu/sulu/src/Sulu/Component/Content/Document/Subscriber/SecuritySubscriber.php:135
         Sulu\Component\Content\Document\Subscriber\SecuritySubscriber->handlePersist() at /var/www/project/vendor/symfony/event-dispatcher/EventDispatcher.php:270
         Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}() at /var/www/project/vendor/symfony/event-dispatcher/EventDispatcher.php:230
         Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /var/www/project/vendor/symfony/event-dispatcher/EventDispatcher.php:59
         Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /var/www/project/vendor/sulu/sulu/src/Sulu/Component/DocumentManager/DocumentManager.php:57
         Sulu\Component\DocumentManager\DocumentManager->persist() at /var/www/project/vendor/sulu/sulu/src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php:123
         Sulu\Component\Webspace\Document\Initializer\WebspaceInitializer->initializeWebspace() at /var/www/project/vendor/sulu/sulu/src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php:70
         Sulu\Component\Webspace\Document\Initializer\WebspaceInitializer->initialize() at /var/www/project/vendor/sulu/sulu/src/Sulu/Bundle/DocumentManagerBundle/Initializer/Initializer.php:61
         Sulu\Bundle\DocumentManagerBundle\Initializer\Initializer->initialize() at /var/www/project/vendor/sulu/sulu/src/Sulu/Bundle/DocumentManagerBundle/Command/InitializeCommand.php:80
         Sulu\Bundle\DocumentManagerBundle\Command\InitializeCommand->execute() at /var/www/project/vendor/symfony/console/Command/Command.php:255
         Symfony\Component\Console\Command\Command->run() at /var/www/project/vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Build/SuluBuilder.php:68
         Sulu\Bundle\CoreBundle\Build\SuluBuilder->execCommand() at /var/www/project/vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Build/PhpcrBuilder.php:43
         Sulu\Bundle\CoreBundle\Build\PhpcrBuilder->build() at /var/www/project/vendor/massive/build-bundle/Command/BuildCommand.php:195
         Massive\Bundle\BuildBundle\Command\BuildCommand->runBuilders() at /var/www/project/vendor/massive/build-bundle/Command/BuildCommand.php:123
         Massive\Bundle\BuildBundle\Command\BuildCommand->execute() at /var/www/project/vendor/symfony/console/Command/Command.php:255
         Symfony\Component\Console\Command\Command->run() at /var/www/project/vendor/symfony/console/Application.php:989
         Symfony\Component\Console\Application->doRunCommand() at /var/www/project/vendor/symfony/framework-bundle/Console/Application.php:96
         Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/project/vendor/symfony/console/Application.php:290
         Symfony\Component\Console\Application->doRun() at /var/www/project/vendor/symfony/framework-bundle/Console/Application.php:82
         Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/project/vendor/symfony/console/Application.php:166
         Symfony\Component\Console\Application->run() at /var/www/project/bin/console.php:51
         include() at /var/www/project/bin/adminconsole:7
        
        In Client.php line 1417:
                                                                     
          [PHPCR\ItemNotFoundException]                              
          Item /cmf/dy/contents not found in workspace default_live  
                                                                     
        
        Exception trace:
          at /var/www/project/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/Client.php:1417
         Jackalope\Transport\DoctrineDBAL\Client->getNode() at /var/www/project/vendor/jackalope/jackalope/src/Jackalope/ObjectManager.php:214
         Jackalope\ObjectManager->getNodeByPath() at /var/www/project/vendor/jackalope/jackalope/src/Jackalope/Session.php:279
         Jackalope\Session->getNode() at /var/www/project/vendor/sulu/sulu/src/Sulu/Bundle/DocumentManagerBundle/Session/Session.php:84
         Sulu\Bundle\DocumentManagerBundle\Session\Session->getNode() at /var/www/project/vendor/sulu/sulu/src/Sulu/Component/Content/Document/Subscriber/SecuritySubscriber.php:220
         Sulu\Component\Content\Document\Subscriber\SecuritySubscriber->getLiveNode() at /var/www/project/vendor/sulu/sulu/src/Sulu/Component/Content/Document/Subscriber/SecuritySubscriber.php:135
         Sulu\Component\Content\Document\Subscriber\SecuritySubscriber->handlePersist() at /var/www/project/vendor/symfony/event-dispatcher/EventDispatcher.php:270
         Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}() at /var/www/project/vendor/symfony/event-dispatcher/EventDispatcher.php:230
         Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /var/www/project/vendor/symfony/event-dispatcher/EventDispatcher.php:59
         Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /var/www/project/vendor/sulu/sulu/src/Sulu/Component/DocumentManager/DocumentManager.php:57
         Sulu\Component\DocumentManager\DocumentManager->persist() at /var/www/project/vendor/sulu/sulu/src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php:123
         Sulu\Component\Webspace\Document\Initializer\WebspaceInitializer->initializeWebspace() at /var/www/project/vendor/sulu/sulu/src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php:70
         Sulu\Component\Webspace\Document\Initializer\WebspaceInitializer->initialize() at /var/www/project/vendor/sulu/sulu/src/Sulu/Bundle/DocumentManagerBundle/Initializer/Initializer.php:61
         Sulu\Bundle\DocumentManagerBundle\Initializer\Initializer->initialize() at /var/www/project/vendor/sulu/sulu/src/Sulu/Bundle/DocumentManagerBundle/Command/InitializeCommand.php:80
         Sulu\Bundle\DocumentManagerBundle\Command\InitializeCommand->execute() at /var/www/project/vendor/symfony/console/Command/Command.php:255
         Symfony\Component\Console\Command\Command->run() at /var/www/project/vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Build/SuluBuilder.php:68
         Sulu\Bundle\CoreBundle\Build\SuluBuilder->execCommand() at /var/www/project/vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Build/PhpcrBuilder.php:43
         Sulu\Bundle\CoreBundle\Build\PhpcrBuilder->build() at /var/www/project/vendor/massive/build-bundle/Command/BuildCommand.php:195
         Massive\Bundle\BuildBundle\Command\BuildCommand->runBuilders() at /var/www/project/vendor/massive/build-bundle/Command/BuildCommand.php:123
         Massive\Bundle\BuildBundle\Command\BuildCommand->execute() at /var/www/project/vendor/symfony/console/Command/Command.php:255
         Symfony\Component\Console\Command\Command->run() at /var/www/project/vendor/symfony/console/Application.php:989
         Symfony\Component\Console\Application->doRunCommand() at /var/www/project/vendor/symfony/framework-bundle/Console/Application.php:96
         Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/project/vendor/symfony/console/Application.php:290
         Symfony\Component\Console\Application->doRun() at /var/www/project/vendor/symfony/framework-bundle/Console/Application.php:82
         Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/project/vendor/symfony/console/Application.php:166
         Symfony\Component\Console\Application->run() at /var/www/project/bin/console.php:51
         include() at /var/www/project/bin/adminconsole:7
        
        sulu:build [-D|--nodeps] [-k|--keep-exit-code] [--destroy] [--] [<target>]
        
```
```
➜  project git:(update-2.2.1) composer info
behat/transliterator                     v1.3.0    String transliterator
brick/math                               0.9.1     Arbitrary-precision arithmetic library
clue/stream-filter                       v1.5.0    A simple and modern approach to stream filtering in PHP
composer/package-versions-deprecated     1.11.99.1 Composer plugin that provides efficient querying for installed package versions (no runtime IO)
contao/imagine-svg                       1.0.2     Contao Imagine SVG library
dantleech/glob-finder                    1.0.0     Library offering object location from hierarchrical persistent storage systems using globs
dantleech/phpcr-migrations-bundle        1.2.0     PHPCR migrations bundle
deployer/deployer                        v6.8.0    Deployment Tool
deployer/phar-update                     v2.2.0    Integrates Phar Update to Symfony Console.
deployer/recipes                         6.2.2     3rd party deployer recipes
doctrine/annotations                     1.11.1    Docblock Annotations Parser
doctrine/cache                           1.10.2    PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/collections                     1.6.7     PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                          2.13.3    PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, p...
doctrine/data-fixtures                   1.4.4     Data Fixtures for all Doctrine Object Managers
doctrine/dbal                            2.10.4    Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle                 2.2.2     Symfony DoctrineBundle
doctrine/doctrine-fixtures-bundle        3.4.0     Symfony DoctrineFixturesBundle
doctrine/event-manager                   1.1.1     The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                       1.4.3     PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator                    1.4.0     A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                           1.2.1     PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/orm                             2.7.5     Object-Relational-Mapper for PHP
doctrine/persistence                     1.3.8     The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/phpcr-bundle                    2.1.2     Symfony DoctrinePHPCRBundle
doctrine/reflection                      1.2.2     The Doctrine Reflection project is a simple library used by the various Doctrine projects which adds some additional functionality on top of the reflection...
doctrine/sql-formatter                   1.1.1     a PHP SQL highlighting library
dragonmantank/cron-expression            v3.1.0    CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
egulias/email-validator                  2.1.24    A library for validating emails against several RFCs
friendsofsymfony/http-cache              2.10.0    Tools to manage HTTP caching proxies with PHP
friendsofsymfony/http-cache-bundle       2.9.1     Set path based HTTP cache headers and send invalidation requests to your HTTP cache
friendsofsymfony/jsrouting-bundle        2.7.0     A pretty nice way to expose your Symfony2 routing to client applications.
friendsofsymfony/rest-bundle             3.0.3     This Bundle provides various tools to rapidly develop RESTful API's with Symfony
gedmo/doctrine-extensions                v2.4.42   Doctrine2 behavioral extensions
goodby/csv                               1.3.0     CSV import/export library
guzzlehttp/guzzle                        6.5.5     Guzzle is a PHP HTTP client library
guzzlehttp/promises                      1.4.0     Guzzle promises library
guzzlehttp/psr7                          1.7.0     PSR-7 message implementation that also provides common utility methods
handcraftedinthealps/rest-routing-bundle 1.0.0     This bundle provides automatic route registration for the Controllers
handcraftedinthealps/zendsearch          2.0.0     a general purpose text search engine written entirely in PHP 5
imagine/imagine                          1.2.4     Image processing for PHP 5.3
jackalope/jackalope                      1.4.2     Jackalope PHPCR library
jackalope/jackalope-doctrine-dbal        1.5.1     Jackalope Transport library for Doctrine DBAL
jms/metadata                             2.4.0     Class/method/property metadata management in PHP
jms/serializer                           3.10.0    Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle                    3.7.0     Allows you to easily serialize, and deserialize data of any complexity
layershifter/tld-database                1.0.69    Database abstraction for Public Suffix List
layershifter/tld-extract                 2.0.1     TLDExtract, library for extracting parts of domain, e.q. domain parser
layershifter/tld-support                 1.1.1     Support package for TLDDatabase and TLDExtract
massive/build-bundle                     0.5.3     Massive Art Build Bundle
massive/search-bundle                    2.4.1     Massive Search Bundle
monolog/monolog                          2.1.1     Sends your logs to files, sockets, inboxes, databases and various web services
mustangostang/spyc                       0.6.3     A simple YAML loader/dumper class for PHP
ocramius/proxy-manager                   2.2.3     A library providing utilities to generate, instantiate and generally operate with Object Proxies
oro/doctrine-extensions                  1.3.0     Doctrine Extensions for MySQL and PostgreSQL.
pagerfanta/pagerfanta                    v2.5.1    Pagination for PHP
php-http/client-common                   2.3.0     Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                       1.13.0    Finds installed HTTPlug implementations and PSR-7 message factories
php-http/guzzle6-adapter                 v2.0.1    Guzzle 6 HTTP Adapter
php-http/httplug                         2.2.0     HTTPlug, the HTTP client abstraction for PHP
php-http/message                         1.10.0    HTTP Message related tools
php-http/message-factory                 v1.0.2    Factory interfaces for PSR-7 HTTP Message
php-http/promise                         1.1.0     Promise used for asynchronous HTTP requests
phpcr/phpcr                              2.1.6     PHP Content Repository interfaces
phpcr/phpcr-migrations                   1.2.0     Migrations for PHPCR
phpcr/phpcr-shell                        1.2.1     Shell for PHPCR
phpcr/phpcr-utils                        1.5.1     PHP Content Repository implementation independant utilities
pimple/pimple                            v3.3.1    Pimple, a simple Dependency Injection Container
piwik/device-detector                    3.13.1    The Universal Device Detection library, that parses User Agents and detects devices (desktop, tablet, mobile, tv, cars, console, etc.), clients (browsers, ...
psr/cache                                1.0.1     Common interface for caching libraries
psr/container                            1.0.0     Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                     1.0.0     Standard interfaces for event handling.
psr/http-client                          1.0.1     Common interface for HTTP clients
psr/http-factory                         1.0.1     Common interfaces for PSR-7 HTTP message factories
psr/http-message                         1.0.1     Common interface for HTTP messages
psr/log                                  1.1.3     Common interface for logging libraries
ralouphie/getallheaders                  3.0.3     A polyfill for getallheaders.
ramsey/collection                        1.1.1     A PHP 7.2+ library for representing and manipulating collections.
ramsey/uuid                              4.1.1     A PHP library for generating and working with universally unique identifiers (UUIDs).
stof/doctrine-extensions-bundle          v1.5.0    Integration of the gedmo/doctrine-extensions with Symfony2
sulu/sulu                                2.2.2     Core framework that implements the functionality of the Sulu content management system
sulu/web-twig                            v2.4.1    The web twig extension for web-js component management
swiftmailer/swiftmailer                  v6.2.3    Swiftmailer, free feature-rich PHP mailer
symfony-cmf/routing                      2.3.3     Extends the Symfony routing component for dynamic routes and chaining several routers
symfony-cmf/routing-bundle               2.4.2     Symfony RoutingBundle
symfony-cmf/slugifier-api                2.0.0     Provides a basic slugifier interface to transform text into strings suitable for URLs
symfony/asset                            v5.2.0    Symfony Asset Component
symfony/cache                            v5.2.0    Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts                  v2.2.0    Generic abstractions related to caching
symfony/config                           v5.2.0    Symfony Config Component
symfony/console                          v5.2.0    Symfony Console Component
symfony/css-selector                     v5.2.0    Symfony CssSelector Component
symfony/debug-bundle                     v5.2.0    Symfony DebugBundle
symfony/dependency-injection             v5.2.0    Symfony DependencyInjection Component
symfony/deprecation-contracts            v2.2.0    A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge                  v5.1.9    Symfony Doctrine Bridge
symfony/dom-crawler                      v5.2.0    Symfony DomCrawler Component
symfony/dotenv                           v5.2.0    Registers environment variables from a .env file
symfony/error-handler                    v5.2.0    Symfony ErrorHandler Component
symfony/event-dispatcher                 v5.2.0    Symfony EventDispatcher Component
symfony/event-dispatcher-contracts       v2.2.0    Generic abstractions related to dispatching event
symfony/expression-language              v5.2.0    Symfony ExpressionLanguage Component
symfony/filesystem                       v5.2.0    Symfony Filesystem Component
symfony/finder                           v5.2.0    Symfony Finder Component
symfony/flex                             v1.11.0   Composer plugin for Symfony
symfony/form                             v5.2.0    Symfony Form Component
symfony/framework-bundle                 v5.2.0    Symfony FrameworkBundle
symfony/http-client                      v5.2.0    Symfony HttpClient component
symfony/http-client-contracts            v2.3.1    Generic abstractions related to HTTP clients
symfony/http-foundation                  v5.2.0    Symfony HttpFoundation Component
symfony/http-kernel                      v5.2.0    Symfony HttpKernel Component
symfony/intl                             v5.2.0    A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/lock                             v5.2.0    Symfony Lock Component
symfony/mime                             v5.2.0    A library to manipulate MIME messages
symfony/monolog-bridge                   v5.2.0    Symfony Monolog Bridge
symfony/monolog-bundle                   v3.6.0    Symfony MonologBundle
symfony/options-resolver                 v5.2.0    Symfony OptionsResolver Component
symfony/phpunit-bridge                   v5.2.0    Symfony PHPUnit Bridge
symfony/polyfill-intl-grapheme           v1.20.0   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu                v1.20.0   Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn                v1.20.0   Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer         v1.20.0   Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                v1.20.0   Symfony polyfill for the Mbstring extension
symfony/polyfill-php73                   v1.20.0   Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80                   v1.20.0   Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                          v5.2.0    Symfony Process Component
symfony/property-access                  v5.2.0    Symfony PropertyAccess Component
symfony/property-info                    v5.2.0    Symfony Property Info Component
symfony/proxy-manager-bridge             v5.2.0    Symfony ProxyManager Bridge
symfony/routing                          v5.2.0    Symfony Routing Component
symfony/security-bundle                  v5.2.0    Symfony SecurityBundle
symfony/security-core                    v5.2.0    Symfony Security Component - Core Library
symfony/security-csrf                    v5.2.0    Symfony Security Component - CSRF Library
symfony/security-guard                   v5.2.0    Symfony Security Component - Guard
symfony/security-http                    v5.2.0    Symfony Security Component - HTTP Integration
symfony/serializer                       v5.2.0    Symfony Serializer Component
symfony/service-contracts                v2.2.0    Generic abstractions related to writing services
symfony/string                           v5.2.0    Symfony String component
symfony/swiftmailer-bundle               v3.5.1    Symfony SwiftmailerBundle
symfony/thanks                           v1.2.10   Encourages sending ⭐ and 💵 to fellow PHP package maintainers (not limited to Symfony components)!
symfony/translation                      v5.2.0    Symfony Translation Component
symfony/translation-contracts            v2.3.0    Generic abstractions related to translation
symfony/twig-bridge                      v5.2.0    Symfony Twig Bridge
symfony/twig-bundle                      v5.2.0    Symfony TwigBundle
symfony/validator                        v5.2.0    Symfony Validator Component
symfony/var-dumper                       v5.2.0    Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                     v5.2.0    A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-profiler-bundle              v5.2.0    Symfony WebProfilerBundle
symfony/yaml                             v5.2.0    Symfony Yaml Component
toflar/psr6-symfony-http-cache-store     2.2.2     An alternative store implementation for Symfony's HttpCache reverse proxy that supports auto-pruning of expired entries and cache invalidation by tags.
twig/twig                                v3.1.1    Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                         1.9.1     Assertions to validate method input/output with nice error messages.
willdurand/jsonp-callback-validator      v1.1.0    JSONP callback validator.
willdurand/negotiation                   v2.3.1    Content Negotiation tools for PHP provided as a standalone library.
zendframework/zend-code                  3.4.1     Extensions to the PHP Reflection API, static code scanning, and code generation
zendframework/zend-eventmanager          3.2.1     Trigger and listen to events within a PHP application
```

**Comment by alexander-schranz** [comment]
@kfrohwein the error message looks for me like a database was imported and the [phpcr cache](https://github.com/sulu/skeleton/blob/2.2.2/config/packages/prod/sulu_document_manager.yaml) was not cleared. If its locally you can clear the phpcr cache with:

```yaml
rm -rf var/cache
```

for your prod as I know is multi server setup there the `cache.app` should be a central cache like [redis]https://github.com/sulu/skeleton/blob/66b1916e504292b909987891ef167561e5fbb7ce/config/packages/cache.yaml#L11-L12). There the phpcr cache is not cleared when removing the folders. You can list all cache pools with:

```bash
bin/adminconsole cache:pool:list
```

You can clear all cache pools:

```bash
bin/adminconsole cache:pool:prune
```

You can clear a single cache pool with:

```bash
bin/adminconsole cache:pool:clear cache.app
```

I suggest to run `sulu:build` only when install a project on a new system, on a exist installation you should go with the specific commands like e.g.: `sulu:document:init` when adding a new webspace or localization. When updating a database you should use the `doctrine:migration:*` or if your team does not use migrations using `doctrine:schema:update` command.

**Comment by alexander-schranz** [comment]
Closing this because of inactivity. Please feel to to add additional information here, so we can reopen it when there is still an issue.

**Comment by kfrohwein** [comment]
Hi,

I am back from the dead :slightly_smiling_face: 

It's really an empty and fresh install for local development.

Seems like a kind of race condition.

First sulu does `\Sulu\Component\Webspace\Document\Initializer\WebspaceInitializer::initializeWebspace`

and invokes
```
            $homeDocument = $this->documentManager->find($homePath, null, [
                'load_ghost_content' => false,
                'auto_create' => true,
                'path' => $homePath,
            ]);
```
but after that the document is not created and the next lookup fails with the exception caught before inside `\Sulu\Component\DocumentManager\NodeManager::has`

**Comment by kfrohwein** [comment]
I am lost in the event system. Yes it still looks like a cache problem because I can't find the UUID of the parent note that sulu is using to write the data. Still it seems to get that UUID from somewhere.

So all in all I can say that the event system should persist the new webspace homepage but doesn't. And the next look up of this page fails. Maybe as we are the only one in the world using PGSQL it is a transaction thing. So the data is just not written but I don't know why. I am tempted to change to MySQL for a brief time so I can check if sulu:build works there. But not today.

**Comment by alexander-schranz** [comment]
@kfrohwein does this only happen on `prod` env or also on `dev` env? Only the `prod` env has the phpcr cache active. If you want to run `sulu:build dev` on prod env you need to make clear that you cleared before the phpcr cache which is stored in the `cache.app` which you maybe did configure to be saved in redis so the cache pool clear command is needed as written above. But you could test it if its the cache by try to run sulu:build on `dev` env instead of prod.

**Comment by kfrohwein** [comment]
No redis and it is locally with `APP_ENV=dev`. I tried my prod DB yesterday and I just had to do one doctrine migration and it did run well. So I try our staging system now but that should work.

The only problem I have is doing a fresh, local install of the DEV env without any extra cahing deamon.

```
➜  akona-cms git:(master) docker-compose exec php bin/adminconsole cache:pool:list
 ------------------------------------- 
  Pool name                            
 ------------------------------------- 
  cache.doctrine.orm.default.metadata  
  cache.doctrine.orm.default.result    
  cache.doctrine.orm.default.query     
  cache.app                            
  cache.system                         
  cache.validator                      
  cache.serializer                     
  cache.annotations                    
  cache.property_info                  
  sulu_preview.preview.cache           
  sulu_admin.collaboration_cache       
  cache.security_expression_language   
 ------------------------------------- 
```

**Comment by kfrohwein** [comment]
My best guess is still that the PGSql transaction or something is not flushed after the node should be persisted. But I don't know why. Everything else except PGSql is standard sulu.

**Comment by alexander-schranz** [comment]
@kfrohwein which version of PostgreSQL are you using? Can you test locally if the error also happens with a older postegresql version like 11?

Can you also show the output of:

```bash
bin/adminconsole debug:config framework cache
```

```bash
bin/adminconsole debug:config doctrine_phpcr
```

```bash
bin/adminconsole debug:config doctrine
```

I'm not familiar with postgresql transaction and can not help here. The error is familiar for me only when somebody forgot to delete the caches before running sulu:build on a new or changed database.

If you sure there is no "external" caches (redis or apcu) configured normally `rm -rf var/cache` is enough else caches like maybe needed to be cleared:

```bash
bin/adminconsole cache:pool:clear
bin/adminconsole doctrine:cache:clear-metadata
bin/adminconsole doctrine:cache:clear-result
bin/adminconsole doctrine:cache:clear-query
rm -rf var/cache/*
bin/adminconsole sulu:build dev
```

**Comment by kfrohwein** [comment]
```
➜  akona-cms git:(master) docker-compose exec php bin/adminconsole debug:config framework cache 
Current configuration for "framework.cache"
===========================================

pools:
    sulu_preview.preview.cache:
        adapters:
            - cache.app
        tags: null
        public: false
    sulu_admin.collaboration_cache:
        adapters:
            - cache.adapter.filesystem
        tags: null
        public: false
directory: /var/www/project/var/cache/common/dev/pools
prefix_seed: akona/cms
app: cache.adapter.filesystem
system: cache.adapter.system
default_redis_provider: 'redis://localhost'
default_memcached_provider: 'memcached://localhost'
default_pdo_provider: database_connection
```
```
➜  akona-cms git:(master) docker-compose exec php bin/adminconsole debug:config doctrine_phpcr 

Current configuration for extension with alias "doctrine_phpcr"
===============================================================

doctrine_phpcr:
    session:
        sessions:
            default:
                backend:
                    type: doctrinedbal
                    parameters:
                        jackalope.check_login_on_server: false
                    factory: null
                    logging: false
                    profiling: false
                    backtrace: false
                    curl_options: {  }
                workspace: '%env(PHPCR_WORKSPACE)%'
                username: admin
                password: admin
                admin_username: null
                admin_password: null
                options: {  }
            live:
                backend:
                    type: doctrinedbal
                    parameters:
                        jackalope.check_login_on_server: false
                    factory: null
                    logging: false
                    profiling: false
                    backtrace: false
                    curl_options: {  }
                workspace: '%env(PHPCR_WORKSPACE)%_live'
                username: admin
                password: admin
                admin_username: null
                admin_password: null
                options: {  }
        default_session: default
    dump_max_line_length: 120
    manager_registry_service_id: null
```
```
➜  akona-cms git:(master) docker-compose exec php bin/adminconsole debug:config doctrine      

Current configuration for extension with alias "doctrine"
=========================================================

doctrine:
    orm:
        resolve_target_entities:
            Sulu\Bundle\MediaBundle\Entity\CollectionInterface: Sulu\Bundle\MediaBundle\Entity\Collection
            Sulu\Bundle\ContactBundle\Entity\AccountInterface: Sulu\Bundle\ContactBundle\Entity\Account
        default_entity_manager: default
        entity_managers:
            default:
                mappings:
                    gedmo_tree:
                        type: xml
                        prefix: Gedmo\Tree\Entity
                        dir: /var/www/project/vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity
                        alias: GedmoTree
                        is_bundle: false
                        mapping: true
                    App:
                        is_bundle: false
                        type: annotation
                        dir: /var/www/project/src/Entity
                        prefix: App\Entity
                        alias: App
                        mapping: true
                dql:
                    string_functions:
                        group_concat: Oro\ORM\Query\AST\Functions\String\GroupConcat
                        CAST: Sulu\Component\Rest\DQL\Cast
                    numeric_functions: {  }
                    datetime_functions: {  }
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                query_cache_driver:
                    type: null
                metadata_cache_driver:
                    type: null
                result_cache_driver:
                    type: null
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                filters: {  }
        auto_generate_proxy_classes: true
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        proxy_namespace: Proxies
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_pgsql
                server_version: '12'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
                url: '%env(resolve:DATABASE_URL)%'
                host: localhost
                port: null
                user: root
                password: null
                logging: true
                profiling: true
                profiling_collect_backtrace: false
                profiling_collect_schema_errors: true
                options: {  }
                mapping_types: {  }
                slaves: {  }
                replicas: {  }
                shards: {  }
        types: {  }
```
