### ISSUE TITLE
SuluMediaBundle S3 configuration without credentials

### ISSUE THREAD

**Issue by arjanfrans** [sulu/sulu#5909]
| Q | A
| --- | ---
| Sulu Version | 2.2.6
| PHP Version | 7.4.16
| DB Version | Mysql 5.7

# Actual Behavior

Sulu requires the credentials of the S3 Client to be set. However, the client itself does not require that. The credentials can also for example be set to `false`, see https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_anonymous.html.

![image](https://user-images.githubusercontent.com/3588470/113126272-c449b500-9217-11eb-997d-15f80daf2da8.png)

I am running on an AWS EC2 instances, and the configured IAM roles will allow the S3Client to automatically provide credentials.

# Expected Behavior

Allow the `sulu_media.storages.s3` the same options as the actual S3Client. In my case, I would like to allow the credentials to allow `false` as a value.

# Possible Solutions

As a workaround I have overridden the `sulu_media.storage.s3.client` service to be able to set the `credentials` to `false`.

```
sulu_media:
    storage: s3
    storages:
        s3:
            key: 'dummy'
            secret: 'dummy'
            bucket_name: '%env(AWS_S3_BUCKET)%'
            path_prefix: 'assets'
            region: '%env(AWS_S3_REGION)%'

# Override the sulu service to bypass the credentials requirements
services:
    sulu_media.storage.s3.client:
        class: Aws\S3\S3Client
        arguments:
            - region: "%sulu_media.media.storage.s3.region%"
              version: "%sulu_media.media.storage.s3.version%"
              endpoint: "%sulu_media.media.storage.s3.endpoint%"

              # The application should be running on an EC2 instance, which can automatically connect to S3.
              # Credentials will be generated automatically by this S3 client.
              credentials: false

```
