### ISSUE TITLE
Support nginx cache configuration in SuluHttpCacheBundle

### ISSUE THREAD

**Issue by ampaze** [sulu/sulu#6302]
| Q | A
| --- | ---
| Sulu Version | 2.2.16
| PHP Version | 8.0.8

# Actual Behavior

`Unrecognized option "nginx" under "sulu_http_cache.proxy_client". Available options are "symfony", "varnish".`

# Expected Behavior

I should be able to use nginx as this is supported by FOSHttpCache

# Steps to Reproduce

Edit sulu_http_cache.yaml

```yaml
sulu_http_cache:
    cache:
        max_age: 10
        shared_max_age: 10
    proxy_client:
        nginx:
            enabled: true
```
