### ISSUE TITLE
Using a custom selection field type in page templates throws exception

### ISSUE THREAD

**Issue by fdyckhoff** [sulu/sulu#6607]
| Q | A
| --- | ---
| Sulu Version | 2.3.10
| PHP Version | 7.4
| DB Version | MySQL 
| Browser Version | all

# Actual Behavior

A selection field type for a custom entity does work, when it is configured as described in the documentation and used as a property in a form for another custom entity (in a `config/form/<some-form>.xml` ).

But using the field type in a page template throws an exception: 

>    In ContentTypeManager.php line 51:
>    Content type with alias "review_selection" has not been registered. Known content types are: "number", "text_line", "text_area", "text_editor", "resource_locator", "block", "contact_account_selection", "single_contact_selection", "contact_selection", "single_account_selection", "account_selection", "collection_selection", "single_collection_selection", "media_selection", "single_media_selection", "image_map", "category_selection", "single_category_selection", "single_snippet_selection", "snippet_selection", "smart_content", "teaser_selection", "page_selection", "single_page_selection", "phone", "segment_select", "password", "url", "email", "date", "datetime", "time", "color", "checkbox", "select", "single_select", "tag_selection", "location", "route", "page_tree_route"     
                                                                                          

# Expected Behavior

The custom selection field type should also work in page and block properties.

# Steps to Reproduce

* Create a custom entity named "Review" and want to add a review_selection field type to select and display reviews on a page.
* Add a review_selection in the sulu_admin > field_type_options configuration like it is described in the documentation: https://docs.sulu.io/en/latest/book/extend-admin.html#selection-field-type
* Add a review_selection property to a page template

# Possible Solutions

I could solve this issue by creating a ReviewSelection Service extending `Sulu\Component\Content\SimpleContentType` and which is more or less a copy of `Sulu\Bundle\ContactBundle\Content\Types\ContactSelection`.

With following service configuration:

```
services:
    app.reference_store.review:
        class: 'Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore'
        tags:
            - { name: 'sulu_website.reference_store', alias: 'review' }
            - { name: 'kernel.reset', method: 'reset' }

    App\Content\Types\ReviewSelection:
        arguments:
            $reviewReferenceStore: '@app.reference_store.review'
        tags:
            - { name: 'sulu.content.type', alias: 'review_selection' }
            - { name: 'sulu.content.export', format: '1.2.xliff', translate: false }

```

So the solution could be to enhance the documentation for selection field types by adding a paragraph that a selection service for the custom entity needs be created as well.

I'm not sure if my solution above is the best way to do it or if there is another way to solve this issue...
