### ISSUE TITLE
Use Geocoder PHP in LocationBundle

### ISSUE THREAD

**Issue by remdan** [sulu/sulu#6740]
# Problem description

I was just wondering why the LocationBundle does not use an existing Geolocator library like "Geocoder PHP"?

Possibly that is worth considering...
[The most featured Geocoder library written in PHP](https://geocoder-php.org/)

# Proposed solution

[existing Symfony integration](https://github.com/geocoder-php/BazingaGeocoderBundle)

**Comment by alexander-schranz** [comment]
We currently as I know only have providers in it which we can directly call. This did at current state made the maintainance for us really low as we don't depend on third party library which mostly we need to make sure support latest PHP or Symfony Versions. We must also say that the LocationBundle is not used a lot most are happy with the OpenStreetMap providers nominatim.

But if you say it is well known and good maintained over years it could be integrated the same way as we currently implemented "Flysystem" adapters for storage as an "Optional Provider" by creating a "Bridge" to the Bundle you mention. So if the Bundle is available an additional "Bridge" service can then be registrered.

So as a more clear example it could be configured in the location bundle something like this:

So maybe something like:

```yaml
sulu_location:
    geolocator: 'geocoder'
    geolocators:
        # others
        geocoder:
            service: 'geocoder_service' # as I know geocoder supoprts multiple services
```

If this is configured the service bridge service should be available. The bundle should stay optional and if geocoder is configured and the geocoder bundle not available a exception should be thrown in the LocationBundleExtension.

If you want to give it a try I think we are open for such a pull request.
