### ISSUE TITLE
Add access to calculated size of image formats

### ISSUE THREAD

**Issue by FlorianBoe** [sulu/sulu#6911]
# Problem description
A best practice to optimize the Cumulative Layout Shift of images is to specify the height and width of the image. For image formats that are only limited by width, this is currently not possible. In these cases I can't determine the size of the images via the configured aspect ratio. Currently only the width and height of the source file can be accessed (`media.properties.width` and `media.properties.height`).

Also image formats with a defined width and height would benefit from this feature, since height and width do not have to be derived by separating the image format key (for example by splitting the `300x400` string).

# Proposed solution

The media object could be extended by a dimensions (or otherwise named) property containing an array of the image format keys and the size values.

**Comment by alexander-schranz** [comment]
Hello @FlorianBoe,

We recommend here the usage of the `get_image` twig extension of the `sulu/web-twig` project. It already provides you a full pictures tags including `width` and `height` attributes by the `properties` value of the image.

See https://github.com/sulu/web-twig/blob/2.5/docs/image.md

Because of history of the package, to enable the full potential of that twig extension you need to enable the specific features. The following configuration currently is recommended:

```yaml
Sulu\Twig\Extensions\ImageExtension:
    arguments:
        $defaultAttributes:
            loading: 'lazy'
        $defaultAdditionalTypes:
            webp: 'image/webp'
        $aspectRatio: true
        $imageFormatConfiguration: '%sulu_media.image.formats%'
```

This way you get an img tag with width and height avoiding the layout shifts and also a picture tag including webp variants of the image.

PS: the width and height are also without the extension available under `media.properties.width` or `media.properties.height` if the upload could calculate it, based on that you can calculate the format width and height, but if you just use the exist extension you don't need todo that yourself.
