### ISSUE TITLE
Active hovered icon buttons are not correctly styled

### ISSUE THREAD

**Issue by Jupi007** [sulu/sulu#6925]
| Q | A
| --- | ---
| Sulu Version | 2.5.4
| Browser Version | Firefox 107.0.1

# Actual Behavior

Hover an active icon button use_not active_ hover background color + _active_ text color:

![image](https://user-images.githubusercontent.com/36476595/205454919-6ecec83b-fdea-4439-ab33-c81ab2dc453a.png)
_normal, active, active hovered_

# Expected Behavior

The button background color should be correctly styled.

# Steps to Reproduce

Go to the media page, and hover an active button (like the ones about grid/list view).

# Possible Solutions

The solution is to add a specific style for this case.
Use the `$scorpion: #585858` color looks good imo:

```scss
$iconBackgroundColorActiveHover: $scorpion;
// ...
.icon {
    // ...
    &:hover:not(:disabled) {
        /// ...
        &.active {
            background-color: $iconBackgroundColorActiveHover;
        }
    }
}
```

![Capture d’écran du 2022-12-03 19-05-00](https://user-images.githubusercontent.com/36476595/205455464-6df1a1df-bde5-4c4d-a5a8-43ab21dd0142.png)

---

Also, off-topic but there are `$iconBackgroundColor***` vars which are not used on top of the `button.scss` file:

https://github.com/sulu/sulu/blob/8ed3425211e8b72b4ac7ecc5239842408927fc42/src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/button.scss#L24-L25
