### ISSUE TITLE
Add LegacyPasswordHasher with PasswordMigration for easier upgrade of older Sulu

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#6986]
# Problem description

Add LegacyPasswordHasher for easier upgrade of older Sulu's. The hash based password encoder from older Sulu like here: https://github.com/sulu/sulu-minimal/blob/00ab2dc917f4557e83bb045826bc824739f8ae86/app/config/admin/security.yml#L6-L10 is not longer possible out of the box. That way we need a LegacyPasswordHasher to provide easier upgrade for this Sulu's from 1.6 to 2.5 with Symfony 6.

# Proposed solution

It should be possible to configure a legacy hasher and use password migration https://symfony.com/doc/current/security/passwords.html#configure-a-new-hasher-using-migrate-from.

What need to keep in mind that the exist bcrypt works still like expected, when add the Hash Interface to the User for the LegacyPasswordHasher. If that is not the case the part with the Interface on the User need instead be documented.

As I remember also the `LegacyPasswordAuthenticationInterface` was required to be set on the User: https://github.com/symfony/symfony/blob/1f4a1bc8d90d01badc194fea71418a56da82da57/src/Symfony/Component/Security/Core/User/LegacyPasswordAuthenticatedUserInterface.php#L22-L28. It need to be tested if that does not have effect for existing bycrypt installations.

/cc @mario-fehr @thomasduenser 

---

If possible target 2.5 else 2.6 branch for this.

**Comment by domaingood** [comment]
most commonly used nowadays is bcrypt hashing method

**Comment by alexander-schranz** [comment]
@domaingood `bcrypt` ist the default for all new installations since 2.0: https://github.com/sulu/skeleton/blob/78b0da1109164e1c4bb5473ac15437175d5083ec/config/packages/security.yaml#L10-L11. When impelmenting the password upgrader it should so automatically migrated to bcrypt. Or if we change to use `auto` to the `auto` configured default value which also currently is bcrypt by Symfony: https://symfony.com/doc/current/security/passwords.html#the-auto-hasher

**Comment by nikomuse** [comment]
I successfully got it right with a legacy hasher (from old projects in SF 1.4 :alien: ), encrypting new password and old ones at login with **sodium** (argon2). So I share my findings here.
I chose sodium but it could be bcrypt as main hasher with just a legacy one.
It's been tested with **Sulu 2.5.4** and **SF 6.2.7**.

As written in the [Symfony documentation](https://symfony.com/doc/6.3/security/passwords.html#upgrade-the-password) , as Sulu has a custom user provider, this solution should be implemented. I tested the Doctrine's entity user provider solution but it doesn't work.

Here is my _security.yaml_ where I declare my legacy sf14_hasher :
```
security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        sf14_hasher:
            id: 'App\Security\Hasher\Sf14PasswordHasher'

        App\Entity\User:
            algorithm: sodium
            migrate_from:
                - bcrypt
                - sf14_hasher

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        sulu:
            id: sulu_security.user_provider
```

The _services.yaml_ to override the Sulu User provider :
```
services:
        sulu_security.user_provider:
                class: App\Security\UserProvider
```

My custom SF 1.4 hasher that implements _LegacyPasswordHasherInterface_ to get the salt :
```
<?php

namespace App\Security\Hasher;

use Symfony\Component\PasswordHasher\Exception\InvalidPasswordException;
use Symfony\Component\PasswordHasher\Hasher\CheckPasswordLengthTrait;
use Symfony\Component\PasswordHasher\LegacyPasswordHasherInterface;


class Sf14PasswordHasher implements _LegacyPasswordHasherInterface_
{
    use CheckPasswordLengthTrait;

    public function hash(#[\SensitiveParameter] string $plainPassword, string $salt = null): string
    {
        if ($this->isPasswordTooLong($plainPassword)) {
            throw new InvalidPasswordException();
        }
        $hashedPassword = sha1($salt.$plainPassword);
        return $hashedPassword;
    }

    public function verify(string $hashedPassword, #[\SensitiveParameter] string $plainPassword, string $salt = null): bool
    {
        if ('' === $plainPassword || $this->isPasswordTooLong($plainPassword)) {
            return false;
        }
        $passwordIsValid = $hashedPassword === $this->hash($plainPassword, $salt);
        return $passwordIsValid;
    }

    public function needsRehash(string $hashedPassword): bool
    {
        // Password hashed with this hasher should never benefit from rehashing...
        return false;
    }
}
```

My custom User to implements _LegacyPasswordAuthenticatedUserInterface_, getSalt needs to return another type to work :
```
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;
use Sulu\Bundle\SecurityBundle\Entity\User as SuluUser;
use Sulu\Bundle\SecurityBundle\Entity\UserRepository;
use Symfony\Component\Security\Core\User\LegacyPasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: 'se_users')]
class User extends SuluUser implements LegacyPasswordAuthenticatedUserInterface {

    /**
     * @return string
     */
    public function __toString(): string {
        return $this->getLastName() . ' ' . $this->getFirstName();
    }

    public function getSalt(): ?string {
        return $this->salt ?? null;
    }
}
```

And finally the overridden UserProvider to implement the _PasswordUpgraderInterface_ : 
```
<?php

namespace App\Security;

use Doctrine\Persistence\ManagerRegistry;
use Sulu\Bundle\SecurityBundle\System\SystemStoreInterface;
use Sulu\Component\Security\Authentication\UserRepositoryInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\PasswordUpgraderInterface;

class UserProvider extends \Sulu\Bundle\SecurityBundle\User\UserProvider implements PasswordUpgraderInterface {

    public function __construct(
        UserRepositoryInterface $userRepository,
        SystemStoreInterface $systemStore,
        private ManagerRegistry $doctrine,
    ) {
        parent::__construct($userRepository, $systemStore);
    }

    public function upgradePassword(PasswordAuthenticatedUserInterface $user, string $newHashedPassword): void {
        $user->setPassword($newHashedPassword);
        $this->doctrine->getManager()->flush();
    }
}
```

Thanks to the Sulu team for their work and responsiveness on the slack channel ! :smiley:

**Comment by alexander-schranz** [comment]
This is fixed in https://github.com/sulu/sulu/pull/7745 thx to @draconivis.

Upgrade from 1.6 should work this way:

```yaml
security:
    # ...
    password_hashers:
        legacy:
            algorithm: sha512
            iterations: 5000
            encode_as_base64: false

        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: bcrypt
            migrate_from:
                - legacy # uses the "legacy" hasher configured above
    # ...
```
