### ISSUE TITLE
How can I upload large file ?

### ISSUE THREAD

**Issue by l396635210** [sulu/sulu#7001]
# Problem description

I want to upload some large file , such as a video exceeding 2G. how can i  segment upload, or upload oss from form page

**Comment by alexander-schranz** [comment]
The limit for the size upload for the admin can be increased in the following config:

```yaml
# config/packages/sulu_media.yaml
sulu_media
    upload:
        max_filesize: 2048
```

Keep in mind your webserver and your php need also support this large files: https://docs.sulu.io/en/2.5/cookbook/web-server/nginx.html#file-upload

If you want to show a progress bar for the upload, you need some kind of JavaScript library doing that for you. Like https://www.dropzone.dev/.
