### ISSUE TITLE
No portal for this url found throws error 500

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#7045]
| Q | A
| --- | ---
| Sulu Version | 2.3.4
| PHP Version | 7.4
| DB Version | MySql 5.7

# Actual Behavior

Following webspace configuration is given:

<environment type="prod">
        <urls>
                <url language="de">www.mywebsite.com/ch-{localization}</url>
                <url language="fr">www.mywebsite.com/ch-{localization}</url>
                <url language="it">www.mywebsite.com/ch-{localization}</url>
        </urls>
</environment>

So if i call `www.mywebsite.com/test` it does not match any portal. But no portal found for this url Error 500 could we get an 404 error instead?

# Expected Behavior

Return a 404 error.

# Steps to Reproduce

Use the configuration above and call `www.mywebsite.com/test`

**Comment by mamazu** [comment]
As discussed in the attached merge request this is intended behaviour. The tldr is a missing portal should be something the developer should look into so "just" returning a 404 would downplay it and nobody would notice. However if you still want that behaviour the code in the merge request still works.

If you are using Symfony 5.4 and higher there is an easier fix with Symfony: https://symfony.com/blog/new-in-symfony-6-3-http-exception-attributes
```yaml
framework:
    exceptions:
        Sulu\Component\Webspace\Analyzer\Exception\UrlMatchNotFoundException:
            log_level: 'debug'
            status_code: 404
```
