### ISSUE TITLE
Sulu HTTP Cache with multiple Varnish servers

### ISSUE THREAD

**Issue by sanhofman** [sulu/sulu#7092]
| Q | A
| --- | ---
| Sulu Version | 2.5.5
| PHP Version | 8.2

# Actual Behavior

1/ While using Sulu with Varnish as caching proxy, we are able to configure 1 Varnish server but while using multiple Varnish replica's we can't seem to configure multiple servers in `sulu_http_cache.yaml`: 

```
when@prod: &prod
    sulu_http_cache:
        debug:
            enabled: true
        tags:
            enabled: true
        cache:
            max_age: 240
            shared_max_age: 480
        proxy_client:
            symfony:
                enabled: false
            varnish:
                enabled: true
                servers: [ "%env(VARNISH_SERVERS)%" ]
                tag_mode: purgekeys
```
With example `VARNISH_SERVERS=varnish:80,varnish_rep1:82,varnish_rep2:83`

It gets processed as 1 server:
`"URL using bad/illegal format or missing URL for "http://"varnish:80,varnish_rep1:82,varnish_rep2:83/"."`

2/ Also while using a custom env processor or json processor, like `servers: '%env(json:VARNISH_SERVERS)%'`

We receive: `Expected one of "bool", "int", "float", "string", but got "array".`

3/ Lastly the FOS HttpCacheBundle has an extra config option `servers_from_jsonenv`, but this doesn't work with sulu_http_cache?

```
                # alternatively, if you configure the varnish servers in an environment variable:
                # servers_from_jsonenv: '%env(json:VARNISH_SERVERS)%'
```

How can we make this work?

**Comment by alexander-schranz** [comment]
Think that would required to be ported to the SuluHttpCache, currently you still can do:

```yaml
symfony:
    proxy_client:
        symfony:
            enabled: false
        varnish:
            enabled: true
            servers:
                - '%env(resolve:VARNISH_SERVER)%'
                - '%env(resolve:VARNISH_SERVER_2)%'
```
