### ISSUE TITLE
CDN url for storage providers

### ISSUE THREAD

**Issue by hual7** [sulu/sulu#7293]
# Problem description
When using storage providers https://docs.sulu.io/en/2.5/cookbook/external-media-storage.html via S3 like AWS, Digitalocean or Cloudflare the redirect path from `/media/ID/download/FILENAME` to the Cloudstorage url will be composed with `$this->endpoint . '/' . $this->bucketName . '/' . \ltrim($path, '/');`

It is not possible to set a CDN url and in case of Cloudflare R2 the redirect to the public files does not work without specifying a CDN url.

# Proposed solution

A separation of API url (endpoint) and CDN url (public) + url check in https://github.com/sulu/sulu/blob/e160828f94181a8eab539afba5ae7eca40dedba2/src/Sulu/Bundle/MediaBundle/Media/Storage/S3Storage.php#L53 would be great.

THX

**Comment by alexander-schranz** [comment]
My prefered solution for this would be that we have a additonal `streamUrl`. Which is just `$path` and we could go over the `Symfony` way of configuring CDNs by providing a asset package.

```twig
{{ asset(media.streamUrl, 'sulu_media') }}
```

And let configure a CDN for it via:

```yaml
framework:
    assets:
        packages:
            sulu_media:
                base_urls: 'http://static_cdn.example.com/%bucketName%/'
```
