### ISSUE TITLE
Custom Route Generator not being called properly.

### ISSUE THREAD

**Issue by matthiasseghers** [sulu/sulu#7318]
| Q | A
| --- | ---
| Sulu Version | 2.5.10
| PHP Version | 8.2.5

# Actual Behavior

When the sulu_route mapping is set to use the type generator, is still uses the default generator instead.

# Expected Behavior

It appears that the generator-type isn't utilized here, as the default one is always used during automatic generation. Currently, there isn't a satisfactory solution for this since Normal route generation depends on the entity, which isn't accessible in the "api" call.
The generator used should be the one defined under the generator key, and the generate method should be called.

# Steps to Reproduce

`sulu_article.yaml`
```yaml
sulu_route:
    mappings:
        Sulu\Bundle\ArticleBundle\Document\ArticleDocument:
            generator: "type"
            options:
                blog: /blog/{implode("-", object)}
                guide: /guides/{implode("-", object)}
```

The `ArtilceRouteGeneratorByType` class will never be called by it's `generate` method, and instead the default one route generation will be called.
