### ISSUE TITLE
Image formats are unnecessarily cached by symfony http cache

### ISSUE THREAD

**Issue by friemt** [sulu/sulu#7521]
| Q | A
| --- | ---
| Sulu Version | 2.5.19
| PHP Version | 8.1
| DB Version | MySQL 8.0
| Browser Version | n/a

# Actual Behavior

When symfony http cache is enabled, additional to the public thumbnail folder at `public/uploads` the image formats are also added to the http cache at `var/cache/common/<env>/http_cache`.

This not only duplicates the space needed to store the files, it should be unnecessary since the thumbnails are ideally served from the public folder by the webserver.

# Expected Behavior

Image formats are only present once on disk.

# Steps to Reproduce

* Take any sulu instance
* Configure symfony http cache
* Call any image by it's website URL
* Check files in `public/uploads` and `var/cache/common/<env>/http_cache`
* Delete the file from `public/uploads`
* Watch the image resurrect from the cache ;)

# Possible Solutions

Exclude the `sulu_media.website.image.proxy` and `sulu_media.website.media.download` from the http cache.

**Comment by friemt** [comment]
**Update:** 
Ok, this workaround is worse than initially thought. While it does remove the images from cache, it also forces all other media, like videos and PDFs, to pass through the whole symfony stack. This performance impact is not acceptable in our use-case.

**Original:**
For anyone affected, this seems a viable workaround:
```
# config/packages/sulu_media.yaml
sulu_media:
    format_manager:
        response_headers:
            Expires: -1
            Pragma: 'no-cache'
            Cache-Control: 'no-cache, public, max-age=0, s-maxage=0'
```
