### ISSUE TITLE
Disabling the request analyser on a static route doesn't work

### ISSUE THREAD

**Issue by mamazu** [sulu/sulu#7598]
| Q | A
| --- | ---
| Sulu Version | 2.6+
| PHP Version | any
| DB Version | Mysql 8
| Browser Version | any

# Actual Behavior

When adding this route to the `config/routes_website.yaml` config, the request processor still is on:
```yaml
stuff:
    path: /stuff
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: test.html.twig
        _requestAnalyzer: false
```

# Expected Behavior
When setting the key in the config the request analyzer should not be run.

# Steps to Reproduce
Add the code above into the file and create a simple `templates/test.html.twig` with a html body.

Then adding a dump in the `src/Sulu/Bundle/WebsiteBundle/EventListener/RouterListener.php` will show you that the attributes in the request are empty. (Because I think the Symfony routing isn't run yet and hasn't found the route.)

# Possible Solutions
* Run the request analyzer after the Symfony router.
* Make it so that the request analyzer can be disabled completely for static content (I don't need portal and webspace info on a static html page)
* Convert the documentation to use Attributes
