### ISSUE TITLE
Preview not working with handler_id configured to session.handler.native_file

### ISSUE THREAD

**Issue by tstauer** [sulu/sulu#7713]
| Q | A
| --- | ---
| Sulu Version | 2.6.6
| PHP Version | 8.2.27
| DB Version | mysql  Ver 8.0.40 for Linux on aarch64 (MySQL Community Server - GPL)
| Browser Version | Firefox ESR 128.5.2esr (64-Bit)

# Actual Behavior
The preview does not work in the environment dev, instead a message "Warning: ini_set(): Session ini settings cannot be changed when a session is active" is shown.

# Expected Behavior

I would expect the preview to render.

# Steps to Reproduce

Configure the session like this:
config/packages/framework.yaml
```
framework:
    session:
        storage_factory_id: session.storage.factory.native
        handler_id: 'session.handler.native_file'
        save_path: '%env(STORAGE_PATH)%/sessions/'
        cookie_secure: auto
        cookie_samesite: lax
        name: SULUSESSID # This avoids conflicts with other applications running on the same domain
```

Then go to admin and try to preview a page:
<img width="1044" alt="Screenshot 2025-01-06 at 14 08 18" src="https://github.com/user-attachments/assets/09ca8bf7-4c4c-4f32-9406-b0582d3188c2" />

# Workaround
Set `handler_id` to `null` in the config.
