### ISSUE TITLE
Integrate ldap authentication

### ISSUE THREAD

**Issue by mamazu** [sulu/sulu#7778]
# Problem description
We already support some Single Sign on provider like OpenId. We could also consider adding support for ldap in the same vein.

# Proposed solution
We could implement this with the `ldap://` protocol in the sso adapter settings.

**Comment by mamazu** [comment]
This would probably be better of in a bundle as it requires a lot of bespoke configuration.

The integration is relatively simple. Configure the Symfony LDAP Services like so:
```php
use Symfony\Component\Ldap\Adapter\ExtLdap\Adapter as LdapAdapter;
use Symfony\Component\Ldap\Ldap;
use Symfony\Component\Ldap\Security\LdapUserProvider;
use Symfony\Component\Security\Core\User\UserProviderInterface;

//...
    $services
        ->set('symfony.component.ldap.ldap.symfony.component.ldap.adapter.extldap.adapter', LdapAdapter::class)
        ->args([
            [
                'host' => '%env(LDAP_HOST)%',
                'port' => '%env(LDAP_PORT)%',
                'encryption' => '%env(LDAP_ENCRYPTION)%',
                'options' => ['protocol_version' => 3, 'referrals' => false],
            ],
        ])
    ;

    $services
        ->set(UserProviderInterface::class, LdapUserProvider::class)
        ->args([
            service('symfony.component.ldap.ldap'),
            '%env(LDAP_USER_QUERY_DN)%',
            '%env(LDAP_LOOKUP_DN)%',
            '%env(LDAP_PASSWORD)%',
            [],
            '',
            '%env(LDAP_QUERY_STRING)%',
            'homeDirectory',
            [],
        ])
    ;

    $services
        ->set('symfony.component.ldap.ldap', Ldap::class)
        ->args([service('symfony.component.ldap.ldap.symfony.component.ldap.adapter.extldap.adapter')])
        ->tag('ldap')
    ;

    // This service is just a wrapper for the Symfony Ldap User Provider to convert the LDAP user to a Sulu user, mostly copy pasted code from Sulu on how to create a user
    $services->set('app.provider.user.admin_user_provider', AdminUserProvider::class);
```
```yaml
    # security-admin.yaml
    providers:
        ldap_provider:
            id: app.provider.user.admin_user_provider
    firewalls:
        admin:
            pattern: ^/
            lazy: true
            entry_point: sulu_security.authentication_entry_point
            provider: ldap_provider
            json_login_ldap:
                check_path: sulu_admin.login_check
                success_handler: sulu_security.authentication_handler
                failure_handler: sulu_security.authentication_handler
                dn_string: '%env(LDAP_USER_QUERY_DN)%'
                query_string: '%env(LDAP_QUERY_STRING)%'
                service: 'symfony.component.ldap.ldap'
                search_dn: '%env(LDAP_LOOKUP_DN)%'
                search_password: '%env(LDAP_PASSWORD)%'
            logout:
                path: sulu_admin.logout
```
