### ISSUE TITLE
Searchable categories tree

### ISSUE THREAD

**Issue by alexanderbuerner** [sulu/sulu#7945]
# Problem description

If you have maaaany categories (we have e.g. 1000) and want to choose one category (e.g. at excerpt and taxonomies), you really have to know where to find it in the tree.

# Proposed solution

Add a search to only show a matching tree-"snapshot"

**Comment by alexanderbuerner** [comment]
I don't know if a design is really required.

1. We could add a new option to the `single_category_selection` "`multiple`" (yes, I know, name "`single_`" makes no sense anymore...), so you can select multiple categories

<img width="568" height="291" alt="Image" src="https://github.com/user-attachments/assets/eb972237-7463-46c4-953f-03d87443895d" />


2. We could add the "default search" of categories to `categories_selection`

<img width="405" height="311" alt="Image" src="https://github.com/user-attachments/assets/8d1d21de-b838-4cad-96af-fed9f5382847" />

<img width="405" height="134" alt="Image" src="https://github.com/user-attachments/assets/08a591a3-3deb-4d53-8f26-d040e5d921b2" />

**Comment by alexander-schranz** [comment]
Currently workaround for this could be use the `list_overlay` adapter.

See https://github.com/sulu/sulu-demo/pull/119

We could by default keep the default as is and add the list_overlay config to core so only:

```yaml
# config/packages/sulu_admin.yaml
sulu_admin:
    field_type_options:
        selection:
            category_selection:
                default_type: 'list_overlay' # change type inside a project to list_overlay by default

                # this could be part of sulu core:
                types:
                    # adds new list overlay config similar to single selection:
                    list_overlay:
                        adapter: 'tree_table_slim'
                        list_key: 'categories'
                        display_properties:
                            - 'name'
                        icon: 'su-tag'
                        label: 'sulu_category.category_selection_label'
                        overlay_title: 'sulu_category.category_selection_overlay_title'
```
