### ISSUE TITLE
Pseudo localization not working

### ISSUE THREAD

**Issue by mamazu** [sulu/sulu#8025]
| Q | A
| --- | ---
| Sulu Version | 2.5+
| PHP Version | *
| DB Version | *
| Browser Version | *

# Actual Behavior
When enabling Symfonys pseudo localization feature to test if the UI to test if everything is translated, Sulu crashes in various places.

# Expected Behavior
Enabling the pseudo localization should work.

# Steps to Reproduce
Set this in your config:
```yaml
framework:
    translator:
        pseudo_localization: true

```
